/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Protocol"
 * 	found in "Ieee1609Dot2Dot1Protocol.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_AcaEeCertResponsePrivateSpdu_H_
#define	_AcaEeCertResponsePrivateSpdu_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Ieee1609Dot2Data-EncryptedSigned.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AcaEeCertResponsePrivateSpdu */
typedef Ieee1609Dot2Data_EncryptedSigned_412P0_t	 AcaEeCertResponsePrivateSpdu_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AcaEeCertResponsePrivateSpdu_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AcaEeCertResponsePrivateSpdu;
asn_struct_free_f AcaEeCertResponsePrivateSpdu_free;
asn_struct_print_f AcaEeCertResponsePrivateSpdu_print;
asn_constr_check_f AcaEeCertResponsePrivateSpdu_constraint;
ber_type_decoder_f AcaEeCertResponsePrivateSpdu_decode_ber;
der_type_encoder_f AcaEeCertResponsePrivateSpdu_encode_der;
xer_type_decoder_f AcaEeCertResponsePrivateSpdu_decode_xer;
xer_type_encoder_f AcaEeCertResponsePrivateSpdu_encode_xer;
jer_type_encoder_f AcaEeCertResponsePrivateSpdu_encode_jer;
oer_type_decoder_f AcaEeCertResponsePrivateSpdu_decode_oer;
oer_type_encoder_f AcaEeCertResponsePrivateSpdu_encode_oer;
per_type_decoder_f AcaEeCertResponsePrivateSpdu_decode_uper;
per_type_encoder_f AcaEeCertResponsePrivateSpdu_encode_uper;
per_type_decoder_f AcaEeCertResponsePrivateSpdu_decode_aper;
per_type_encoder_f AcaEeCertResponsePrivateSpdu_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _AcaEeCertResponsePrivateSpdu_H_ */
#include "asn_internal.h"
