/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1AcaMaInterface"
 * 	found in "Ieee1609Dot2Dot1AcaMaInterface.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_AcaMaInterfacePdu_H_
#define	_AcaMaInterfacePdu_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AcaMaInterfacePdu */
typedef NULL_t	 AcaMaInterfacePdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AcaMaInterfacePdu;
asn_struct_free_f AcaMaInterfacePdu_free;
asn_struct_print_f AcaMaInterfacePdu_print;
asn_constr_check_f AcaMaInterfacePdu_constraint;
ber_type_decoder_f AcaMaInterfacePdu_decode_ber;
der_type_encoder_f AcaMaInterfacePdu_encode_der;
xer_type_decoder_f AcaMaInterfacePdu_decode_xer;
xer_type_encoder_f AcaMaInterfacePdu_encode_xer;
jer_type_encoder_f AcaMaInterfacePdu_encode_jer;
oer_type_decoder_f AcaMaInterfacePdu_decode_oer;
oer_type_encoder_f AcaMaInterfacePdu_encode_oer;
per_type_decoder_f AcaMaInterfacePdu_decode_uper;
per_type_encoder_f AcaMaInterfacePdu_encode_uper;
per_type_decoder_f AcaMaInterfacePdu_decode_aper;
per_type_encoder_f AcaMaInterfacePdu_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _AcaMaInterfacePdu_H_ */
#include "asn_internal.h"
