/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1AcaRaInterface"
 * 	found in "Ieee1609Dot2Dot1AcaRaInterface.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_AcaResponse_H_
#define	_AcaResponse_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AcaEeCertResponsePlainSpdu.h"
#include "AcaEeCertResponsePrivateSpdu.h"
#include "AcaEeCertResponseCubkSpdu.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AcaResponse_PR {
	AcaResponse_PR_NOTHING,	/* No components present */
	AcaResponse_PR_plain,
	AcaResponse_PR_private,
	AcaResponse_PR_cubk
	/* Extensions may appear below */
	
} AcaResponse_PR;

/* AcaResponse */
typedef struct AcaResponse {
	AcaResponse_PR present;
	union AcaResponse_u {
		AcaEeCertResponsePlainSpdu_t	 plain;
		AcaEeCertResponsePrivateSpdu_t	 Private;
		AcaEeCertResponseCubkSpdu_t	 cubk;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AcaResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AcaResponse;
extern asn_CHOICE_specifics_t asn_SPC_AcaResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_AcaResponse_1[3];
extern asn_per_constraints_t asn_PER_type_AcaResponse_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _AcaResponse_H_ */
#include "asn_internal.h"
