/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Acpc"
 * 	found in "Ieee1609Dot2Dot1Acpc.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_AcpcNodeValue_H_
#define	_AcpcNodeValue_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AcpcNodeValue */
typedef OCTET_STRING_t	 AcpcNodeValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AcpcNodeValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AcpcNodeValue;
asn_struct_free_f AcpcNodeValue_free;
asn_struct_print_f AcpcNodeValue_print;
asn_constr_check_f AcpcNodeValue_constraint;
ber_type_decoder_f AcpcNodeValue_decode_ber;
der_type_encoder_f AcpcNodeValue_encode_der;
xer_type_decoder_f AcpcNodeValue_decode_xer;
xer_type_encoder_f AcpcNodeValue_encode_xer;
jer_type_encoder_f AcpcNodeValue_encode_jer;
oer_type_decoder_f AcpcNodeValue_decode_oer;
oer_type_encoder_f AcpcNodeValue_encode_oer;
per_type_decoder_f AcpcNodeValue_decode_uper;
per_type_encoder_f AcpcNodeValue_encode_uper;
per_type_decoder_f AcpcNodeValue_decode_aper;
per_type_encoder_f AcpcNodeValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _AcpcNodeValue_H_ */
#include "asn_internal.h"
