/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_AdvisedTrrContainer_H_
#define	_AdvisedTrrContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TrrDescription.h"
#include "TemporalCharacteristics.h"
#include "KinematicsCharacteristics.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AdvisedTrrContainer */
typedef struct AdvisedTrrContainer {
	TrrDescription_t	 trrDescription;
	TemporalCharacteristics_t	 temporalCharacteristics;
	KinematicsCharacteristics_t	*kinematicsCharacteristics;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AdvisedTrrContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdvisedTrrContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_AdvisedTrrContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_AdvisedTrrContainer_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _AdvisedTrrContainer_H_ */
#include "asn_internal.h"
