/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Protocol"
 * 	found in "Ieee1609Dot2Dot1Protocol.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_AnyMbrPsid_H_
#define	_AnyMbrPsid_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Psid.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AnyMbrPsid */
typedef Psid_t	 AnyMbrPsid_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AnyMbrPsid;
asn_struct_free_f AnyMbrPsid_free;
asn_struct_print_f AnyMbrPsid_print;
asn_constr_check_f AnyMbrPsid_constraint;
ber_type_decoder_f AnyMbrPsid_decode_ber;
der_type_encoder_f AnyMbrPsid_encode_der;
xer_type_decoder_f AnyMbrPsid_decode_xer;
xer_type_encoder_f AnyMbrPsid_encode_xer;
jer_type_encoder_f AnyMbrPsid_encode_jer;
oer_type_decoder_f AnyMbrPsid_decode_oer;
oer_type_encoder_f AnyMbrPsid_encode_oer;
per_type_decoder_f AnyMbrPsid_decode_uper;
per_type_encoder_f AnyMbrPsid_encode_uper;
per_type_decoder_f AnyMbrPsid_decode_aper;
per_type_encoder_f AnyMbrPsid_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _AnyMbrPsid_H_ */
#include "asn_internal.h"
