/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "./ASNfiles/ETSI CAM v1.4.1enh.asn"
 */

#ifndef	_AuxilliaryLinkMac_H_
#define	_AuxilliaryLinkMac_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AuxilliaryLinkMac */
typedef OCTET_STRING_t	 AuxilliaryLinkMac_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AuxilliaryLinkMac;
asn_struct_free_f AuxilliaryLinkMac_free;
asn_struct_print_f AuxilliaryLinkMac_print;
asn_constr_check_f AuxilliaryLinkMac_constraint;
ber_type_decoder_f AuxilliaryLinkMac_decode_ber;
der_type_encoder_f AuxilliaryLinkMac_encode_der;
xer_type_decoder_f AuxilliaryLinkMac_decode_xer;
xer_type_encoder_f AuxilliaryLinkMac_encode_xer;
oer_type_decoder_f AuxilliaryLinkMac_decode_oer;
oer_type_encoder_f AuxilliaryLinkMac_encode_oer;
per_type_decoder_f AuxilliaryLinkMac_decode_uper;
per_type_encoder_f AuxilliaryLinkMac_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AuxilliaryLinkMac_H_ */
#include "asn_internal.h"
