/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941MessagesCa"
 * 	found in "EtsiTs102941MessagesCa.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_ButterflyCertResponseMessage_H_
#define	_ButterflyCertResponseMessage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "EtsiTs103097Data-SignedAndEncrypted-Unicast.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ButterflyCertResponseMessage */
typedef EtsiTs103097Data_SignedAndEncrypted_Unicast_115P0_t	 ButterflyCertResponseMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ButterflyCertResponseMessage;
asn_struct_free_f ButterflyCertResponseMessage_free;
asn_struct_print_f ButterflyCertResponseMessage_print;
asn_constr_check_f ButterflyCertResponseMessage_constraint;
ber_type_decoder_f ButterflyCertResponseMessage_decode_ber;
der_type_encoder_f ButterflyCertResponseMessage_encode_der;
xer_type_decoder_f ButterflyCertResponseMessage_decode_xer;
xer_type_encoder_f ButterflyCertResponseMessage_encode_xer;
jer_type_encoder_f ButterflyCertResponseMessage_encode_jer;
oer_type_decoder_f ButterflyCertResponseMessage_decode_oer;
oer_type_encoder_f ButterflyCertResponseMessage_encode_oer;
per_type_decoder_f ButterflyCertResponseMessage_decode_uper;
per_type_encoder_f ButterflyCertResponseMessage_encode_uper;
per_type_decoder_f ButterflyCertResponseMessage_decode_aper;
per_type_encoder_f ButterflyCertResponseMessage_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ButterflyCertResponseMessage_H_ */
#include "asn_internal.h"
