/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1EeRaInterface"
 * 	found in "Ieee1609Dot2Dot1EeRaInterface.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_ButterflyParamsOriginal_H_
#define	_ButterflyParamsOriginal_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ButterflyExpansion.h"
#include "PublicEncryptionKey.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ButterflyParamsOriginal */
typedef struct ButterflyParamsOriginal {
	ButterflyExpansion_t	 signingExpansion;
	PublicEncryptionKey_t	 encryptionKey;
	ButterflyExpansion_t	 encryptionExpansion;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ButterflyParamsOriginal_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ButterflyParamsOriginal;
extern asn_SEQUENCE_specifics_t asn_SPC_ButterflyParamsOriginal_specs_1;
extern asn_TYPE_member_t asn_MBR_ButterflyParamsOriginal_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ButterflyParamsOriginal_H_ */
#include "asn_internal.h"
