/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "ASNfiles/ETSI CAM v1.4.1enh.asn"
 */

#ifndef	_CAMEnhanced_H_
#define	_CAMEnhanced_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ItsPduHeader.h"
#include "CoopAwarenessEnhanced.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CAMEnhanced */
typedef struct CAMEnhanced {
	ItsPduHeader_t	 header;
	CoopAwarenessEnhanced_t	 cam;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CAMEnhanced_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CAMEnhanced;

#ifdef __cplusplus
}
#endif

#endif	/* _CAMEnhanced_H_ */
#include "asn_internal.h"
