/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "./ASNfiles/ETSI CAM v1.4.1enh.asn"
 */

#ifndef	_CamParametersEnhanced_H_
#define	_CamParametersEnhanced_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BasicContainer.h"
#include "HighFrequencyContainer.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LowFrequencyContainer;
struct SpecialVehicleContainer;
struct ChannelNodeStatusContainer;

/* CamParametersEnhanced */
typedef struct CamParametersEnhanced {
	BasicContainer_t	 basicContainer;
	HighFrequencyContainer_t	 highFrequencyContainer;
	struct LowFrequencyContainer	*lowFrequencyContainer	/* OPTIONAL */;
	struct SpecialVehicleContainer	*specialVehicleContainer	/* OPTIONAL */;
	struct ChannelNodeStatusContainer	*channelNodeStatusContainer	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CamParametersEnhanced_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CamParametersEnhanced;
extern asn_SEQUENCE_specifics_t asn_SPC_CamParametersEnhanced_specs_1;
extern asn_TYPE_member_t asn_MBR_CamParametersEnhanced_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LowFrequencyContainer.h"
#include "SpecialVehicleContainer.h"
#include "ChannelNodeStatusContainer.h"

#endif	/* _CamParametersEnhanced_H_ */
#include "asn_internal.h"
