/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1CertManagement"
 * 	found in "Ieee1609Dot2Dot1CertManagement.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_CertificateChain_H_
#define	_CertificateChain_H_


#include "asn_application.h"

/* Including external dependencies */
#include "MultiSignedCtlSpdu.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CertificateBase;

/* CertificateChain */
typedef struct CertificateChain {
	MultiSignedCtlSpdu_t	 homeCtl;
	struct CertificateChain__others {
		A_SEQUENCE_OF(struct CertificateBase) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} others;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertificateChain_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertificateChain;
extern asn_SEQUENCE_specifics_t asn_SPC_CertificateChain_specs_1;
extern asn_TYPE_member_t asn_MBR_CertificateChain_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CertificateBase.h"

#endif	/* _CertificateChain_H_ */
#include "asn_internal.h"
