/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "./ASNfiles/ETSI CAM v1.4.1enh.asn"
 */

#ifndef	_ChannelNodeStatusContainer_H_
#define	_ChannelNodeStatusContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AuxilliaryLinkMac.h"
#include "AuxilliaryLinkRSSI.h"
#include "CPULoad.h"
#include "RAMLoad.h"
#include "GPULoad.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ChannelNodeStatusContainer */
typedef struct ChannelNodeStatusContainer {
	AuxilliaryLinkMac_t	*auxilliaryLinkMac	/* OPTIONAL */;
	AuxilliaryLinkRSSI_t	*auxilliaryLinkRSSI	/* OPTIONAL */;
	CPULoad_t	 cpuLoad;
	RAMLoad_t	 ramLoad;
	GPULoad_t	 gpuLoad;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChannelNodeStatusContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChannelNodeStatusContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_ChannelNodeStatusContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_ChannelNodeStatusContainer_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _ChannelNodeStatusContainer_H_ */
#include "asn_internal.h"
