/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "./ASNfiles/ETSI CAM v1.4.1enh.asn"
 */

#ifndef	_CPULoad_H_
#define	_CPULoad_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CPULoad {
	CPULoad_zeroUsage	= 0,
	CPULoad_halfUsage	= 5000,
	CPULoad_fullUsage	= 10000,
	CPULoad_unavailable	= 10001
} e_CPULoad;

/* CPULoad */
typedef long	 CPULoad_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CPULoad_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CPULoad;
asn_struct_free_f CPULoad_free;
asn_struct_print_f CPULoad_print;
asn_constr_check_f CPULoad_constraint;
ber_type_decoder_f CPULoad_decode_ber;
der_type_encoder_f CPULoad_encode_der;
xer_type_decoder_f CPULoad_decode_xer;
xer_type_encoder_f CPULoad_encode_xer;
oer_type_decoder_f CPULoad_decode_oer;
oer_type_encoder_f CPULoad_encode_oer;
per_type_decoder_f CPULoad_decode_uper;
per_type_encoder_f CPULoad_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CPULoad_H_ */
#include "asn_internal.h"
