/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2CrlBaseTypes"
 * 	found in "Ieee1609Dot2CrlBaseTypes.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_CrlContents_H_
#define	_CrlContents_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Uint8.h"
#include "CrlSeries.h"
#include "HashedId8.h"
#include "Time32.h"
#include "CrlPriorityInfo.h"
#include "ToBeSignedHashIdCrl.h"
#include "ToBeSignedLinkageValueCrl.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CrlContents__typeSpecific_PR {
	CrlContents__typeSpecific_PR_NOTHING,	/* No components present */
	CrlContents__typeSpecific_PR_fullHashCrl,
	CrlContents__typeSpecific_PR_deltaHashCrl,
	CrlContents__typeSpecific_PR_fullLinkedCrl,
	CrlContents__typeSpecific_PR_deltaLinkedCrl
	/* Extensions may appear below */
	
} CrlContents__typeSpecific_PR;

/* CrlContents */
typedef struct CrlContents {
	Uint8_t	 version;
	CrlSeries_t	 crlSeries;
	HashedId8_t	 cracaId;
	Time32_t	 issueDate;
	Time32_t	 nextCrl;
	CrlPriorityInfo_t	 priorityInfo;
	struct CrlContents__typeSpecific {
		CrlContents__typeSpecific_PR present;
		union CrlContents__typeSpecific_u {
			ToBeSignedHashIdCrl_t	 fullHashCrl;
			ToBeSignedHashIdCrl_t	 deltaHashCrl;
			ToBeSignedLinkageValueCrl_t	 fullLinkedCrl;
			ToBeSignedLinkageValueCrl_t	 deltaLinkedCrl;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} typeSpecific;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CrlContents_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CrlContents;

#ifdef __cplusplus
}
#endif

#endif	/* _CrlContents_H_ */
#include "asn_internal.h"
