/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Crl"
 * 	found in "Ieee1609Dot2Crl.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_CrlPsid_H_
#define	_CrlPsid_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Psid.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CrlPsid */
typedef Psid_t	 CrlPsid_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CrlPsid;
asn_struct_free_f CrlPsid_free;
asn_struct_print_f CrlPsid_print;
asn_constr_check_f CrlPsid_constraint;
ber_type_decoder_f CrlPsid_decode_ber;
der_type_encoder_f CrlPsid_encode_der;
xer_type_decoder_f CrlPsid_decode_xer;
xer_type_encoder_f CrlPsid_encode_xer;
jer_type_encoder_f CrlPsid_encode_jer;
oer_type_decoder_f CrlPsid_decode_oer;
oer_type_encoder_f CrlPsid_encode_oer;
per_type_decoder_f CrlPsid_decode_uper;
per_type_encoder_f CrlPsid_encode_uper;
per_type_decoder_f CrlPsid_decode_aper;
per_type_encoder_f CrlPsid_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CrlPsid_H_ */
#include "asn_internal.h"
