/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941TrustLists"
 * 	found in "EtsiTs102941TrustLists.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_CtlFormat_H_
#define	_CtlFormat_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Version.h"
#include "Time32.h"
#include "BOOLEAN.h"
#include "NativeInteger.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CtlCommand;

/* CtlFormat */
typedef struct CtlFormat {
	Version_t	 version;
	Time32_t	 nextUpdate;
	BOOLEAN_t	 isFullCtl;
	long	 ctlSequence;
	struct CtlFormat__ctlCommands {
		A_SEQUENCE_OF(struct CtlCommand) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ctlCommands;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CtlFormat_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CtlFormat;
extern asn_SEQUENCE_specifics_t asn_SPC_CtlFormat_specs_1;
extern asn_TYPE_member_t asn_MBR_CtlFormat_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CtlCommand.h"

#endif	/* _CtlFormat_H_ */
#include "asn_internal.h"
