/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1CertManagement"
 * 	found in "Ieee1609Dot2Dot1CertManagement.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_CtlInfoStatus_H_
#define	_CtlInfoStatus_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ElectorGroupId.h"
#include "CtlSequenceNumber.h"
#include "Time32.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CtlInfoStatus */
typedef struct CtlInfoStatus {
	ElectorGroupId_t	 electorGroupId;
	CtlSequenceNumber_t	 sequenceNumber;
	Time32_t	 lastUpdate;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CtlInfoStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CtlInfoStatus;
extern asn_SEQUENCE_specifics_t asn_SPC_CtlInfoStatus_specs_1;
extern asn_TYPE_member_t asn_MBR_CtlInfoStatus_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _CtlInfoStatus_H_ */
#include "asn_internal.h"
