/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1CertManagement"
 * 	found in "Ieee1609Dot2Dot1CertManagement.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_CtlRootCaEntry_H_
#define	_CtlRootCaEntry_H_


#include "asn_application.h"

/* Including external dependencies */
#include "HashedId32.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CtlRootCaEntry */
typedef HashedId32_t	 CtlRootCaEntry_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CtlRootCaEntry_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CtlRootCaEntry;
asn_struct_free_f CtlRootCaEntry_free;
asn_struct_print_f CtlRootCaEntry_print;
asn_constr_check_f CtlRootCaEntry_constraint;
ber_type_decoder_f CtlRootCaEntry_decode_ber;
der_type_encoder_f CtlRootCaEntry_encode_der;
xer_type_decoder_f CtlRootCaEntry_decode_xer;
xer_type_encoder_f CtlRootCaEntry_encode_xer;
jer_type_encoder_f CtlRootCaEntry_encode_jer;
oer_type_decoder_f CtlRootCaEntry_decode_oer;
oer_type_encoder_f CtlRootCaEntry_encode_oer;
per_type_decoder_f CtlRootCaEntry_decode_uper;
per_type_encoder_f CtlRootCaEntry_encode_uper;
per_type_decoder_f CtlRootCaEntry_decode_aper;
per_type_encoder_f CtlRootCaEntry_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CtlRootCaEntry_H_ */
#include "asn_internal.h"
