/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1CertManagement"
 * 	found in "Ieee1609Dot2Dot1CertManagement.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_CtlSequenceNumber_H_
#define	_CtlSequenceNumber_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CtlSequenceNumber */
typedef long	 CtlSequenceNumber_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CtlSequenceNumber_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CtlSequenceNumber;
asn_struct_free_f CtlSequenceNumber_free;
asn_struct_print_f CtlSequenceNumber_print;
asn_constr_check_f CtlSequenceNumber_constraint;
ber_type_decoder_f CtlSequenceNumber_decode_ber;
der_type_encoder_f CtlSequenceNumber_encode_der;
xer_type_decoder_f CtlSequenceNumber_decode_xer;
xer_type_encoder_f CtlSequenceNumber_encode_xer;
jer_type_encoder_f CtlSequenceNumber_encode_jer;
oer_type_decoder_f CtlSequenceNumber_decode_oer;
oer_type_encoder_f CtlSequenceNumber_encode_oer;
per_type_decoder_f CtlSequenceNumber_decode_uper;
per_type_encoder_f CtlSequenceNumber_encode_uper;
per_type_decoder_f CtlSequenceNumber_decode_aper;
per_type_encoder_f CtlSequenceNumber_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CtlSequenceNumber_H_ */
#include "asn_internal.h"
