/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1EcaEeInterface"
 * 	found in "Ieee1609Dot2Dot1EcaEeInterface.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_EcaEeInterfacePdu_H_
#define	_EcaEeInterfacePdu_H_


#include "asn_application.h"

/* Including external dependencies */
#include "EeEcaCertRequest.h"
#include "EcaEeCertResponse.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EcaEeInterfacePdu_PR {
	EcaEeInterfacePdu_PR_NOTHING,	/* No components present */
	EcaEeInterfacePdu_PR_eeEcaCertRequest,
	EcaEeInterfacePdu_PR_ecaEeCertResponse
	/* Extensions may appear below */
	
} EcaEeInterfacePdu_PR;

/* EcaEeInterfacePdu */
typedef struct EcaEeInterfacePdu {
	EcaEeInterfacePdu_PR present;
	union EcaEeInterfacePdu_u {
		EeEcaCertRequest_t	 eeEcaCertRequest;
		EcaEeCertResponse_t	 ecaEeCertResponse;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EcaEeInterfacePdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EcaEeInterfacePdu;
extern asn_CHOICE_specifics_t asn_SPC_EcaEeInterfacePdu_specs_1;
extern asn_TYPE_member_t asn_MBR_EcaEeInterfacePdu_1[2];
extern asn_per_constraints_t asn_PER_type_EcaEeInterfacePdu_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _EcaEeInterfacePdu_H_ */
#include "asn_internal.h"
