/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Protocol"
 * 	found in "Ieee1609Dot2Dot1Protocol.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_EcaEeCertResponseSpdu_H_
#define	_EcaEeCertResponseSpdu_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Ieee1609Dot2Data-Signed.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EcaEeCertResponseSpdu */
typedef Ieee1609Dot2Data_Signed_246P2_t	 EcaEeCertResponseSpdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EcaEeCertResponseSpdu;
asn_struct_free_f EcaEeCertResponseSpdu_free;
asn_struct_print_f EcaEeCertResponseSpdu_print;
asn_constr_check_f EcaEeCertResponseSpdu_constraint;
ber_type_decoder_f EcaEeCertResponseSpdu_decode_ber;
der_type_encoder_f EcaEeCertResponseSpdu_encode_der;
xer_type_decoder_f EcaEeCertResponseSpdu_decode_xer;
xer_type_encoder_f EcaEeCertResponseSpdu_encode_xer;
jer_type_encoder_f EcaEeCertResponseSpdu_encode_jer;
oer_type_decoder_f EcaEeCertResponseSpdu_decode_oer;
oer_type_encoder_f EcaEeCertResponseSpdu_encode_oer;
per_type_decoder_f EcaEeCertResponseSpdu_decode_uper;
per_type_encoder_f EcaEeCertResponseSpdu_encode_uper;
per_type_decoder_f EcaEeCertResponseSpdu_decode_aper;
per_type_encoder_f EcaEeCertResponseSpdu_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EcaEeCertResponseSpdu_H_ */
#include "asn_internal.h"
