/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1EeMaInterface"
 * 	found in "Ieee1609Dot2Dot1EeMaInterface.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_EeMaInterfacePdu_H_
#define	_EeMaInterfacePdu_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EeMaInterfacePdu */
typedef NULL_t	 EeMaInterfacePdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EeMaInterfacePdu;
asn_struct_free_f EeMaInterfacePdu_free;
asn_struct_print_f EeMaInterfacePdu_print;
asn_constr_check_f EeMaInterfacePdu_constraint;
ber_type_decoder_f EeMaInterfacePdu_decode_ber;
der_type_encoder_f EeMaInterfacePdu_encode_der;
xer_type_decoder_f EeMaInterfacePdu_decode_xer;
xer_type_encoder_f EeMaInterfacePdu_encode_xer;
jer_type_encoder_f EeMaInterfacePdu_encode_jer;
oer_type_decoder_f EeMaInterfacePdu_decode_oer;
oer_type_encoder_f EeMaInterfacePdu_encode_oer;
per_type_decoder_f EeMaInterfacePdu_decode_uper;
per_type_encoder_f EeMaInterfacePdu_encode_uper;
per_type_decoder_f EeMaInterfacePdu_decode_aper;
per_type_encoder_f EeMaInterfacePdu_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EeMaInterfacePdu_H_ */
#include "asn_internal.h"
