/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Protocol"
 * 	found in "Ieee1609Dot2Dot1Protocol.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_EeRaX509AuthenticatedCertRequestSpdu_H_
#define	_EeRaX509AuthenticatedCertRequestSpdu_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Ieee1609Dot2Data-Encrypted.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EeRaX509AuthenticatedCertRequestSpdu */
typedef Ieee1609Dot2Data_Encrypted_290P2_t	 EeRaX509AuthenticatedCertRequestSpdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EeRaX509AuthenticatedCertRequestSpdu;
asn_struct_free_f EeRaX509AuthenticatedCertRequestSpdu_free;
asn_struct_print_f EeRaX509AuthenticatedCertRequestSpdu_print;
asn_constr_check_f EeRaX509AuthenticatedCertRequestSpdu_constraint;
ber_type_decoder_f EeRaX509AuthenticatedCertRequestSpdu_decode_ber;
der_type_encoder_f EeRaX509AuthenticatedCertRequestSpdu_encode_der;
xer_type_decoder_f EeRaX509AuthenticatedCertRequestSpdu_decode_xer;
xer_type_encoder_f EeRaX509AuthenticatedCertRequestSpdu_encode_xer;
jer_type_encoder_f EeRaX509AuthenticatedCertRequestSpdu_encode_jer;
oer_type_decoder_f EeRaX509AuthenticatedCertRequestSpdu_decode_oer;
oer_type_encoder_f EeRaX509AuthenticatedCertRequestSpdu_encode_oer;
per_type_decoder_f EeRaX509AuthenticatedCertRequestSpdu_decode_uper;
per_type_encoder_f EeRaX509AuthenticatedCertRequestSpdu_encode_uper;
per_type_decoder_f EeRaX509AuthenticatedCertRequestSpdu_decode_aper;
per_type_encoder_f EeRaX509AuthenticatedCertRequestSpdu_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EeRaX509AuthenticatedCertRequestSpdu_H_ */
#include "asn_internal.h"
