/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941MessagesItss"
 * 	found in "EtsiTs102941MessagesItss.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_EtsiTs102941MessagesItss_EtsiTs102941DataContent_H_
#define	_EtsiTs102941MessagesItss_EtsiTs102941DataContent_H_


#include "asn_application.h"

/* Including external dependencies */
#include "InnerEcRequestSignedForPop.h"
#include "InnerEcResponse.h"
#include "InnerAtRequest.h"
#include "InnerAtResponse.h"
#include "ToBeSignedCrl.h"
#include "ToBeSignedTlmCtl.h"
#include "ToBeSignedRcaCtl.h"
#include "NULL.h"
#include "ToBeSignedLinkCertificateTlm.h"
#include "EeRaCertRequest.h"
#include "EtsiTs102941ButterflyAuthorizationRequest-X509Signed.h"
#include "RaEeCertInfo.h"
#include "EeRaDownloadRequest.h"
#include "constr_SEQUENCE.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EtsiTs102941MessagesItss_EtsiTs102941DataContent_PR {
	EtsiTs102941MessagesItss_EtsiTs102941DataContent_PR_NOTHING,	/* No components present */
	EtsiTs102941MessagesItss_EtsiTs102941DataContent_PR_enrolmentRequest,
	EtsiTs102941MessagesItss_EtsiTs102941DataContent_PR_enrolmentResponse,
	EtsiTs102941MessagesItss_EtsiTs102941DataContent_PR_authorizationRequest,
	EtsiTs102941MessagesItss_EtsiTs102941DataContent_PR_authorizationResponse,
	EtsiTs102941MessagesItss_EtsiTs102941DataContent_PR_certificateRevocationList,
	EtsiTs102941MessagesItss_EtsiTs102941DataContent_PR_certificateTrustListTlm,
	EtsiTs102941MessagesItss_EtsiTs102941DataContent_PR_certificateTrustListRca,
	EtsiTs102941MessagesItss_EtsiTs102941DataContent_PR_authorizationValidationRequest,
	EtsiTs102941MessagesItss_EtsiTs102941DataContent_PR_authorizationValidationResponse,
	EtsiTs102941MessagesItss_EtsiTs102941DataContent_PR_caCertificateRequest,
	/* Extensions may appear below */
	EtsiTs102941MessagesItss_EtsiTs102941DataContent_PR_linkCertificateTlm,
	EtsiTs102941MessagesItss_EtsiTs102941DataContent_PR_singleSignedLinkCertificateRca,
	EtsiTs102941MessagesItss_EtsiTs102941DataContent_PR_doubleSignedlinkCertificateRca,
	EtsiTs102941MessagesItss_EtsiTs102941DataContent_PR_ext1
} EtsiTs102941MessagesItss_EtsiTs102941DataContent_PR;

/* EtsiTs102941MessagesItss_EtsiTs102941DataContent */
typedef struct EtsiTs102941MessagesItss_EtsiTs102941DataContent {
	EtsiTs102941MessagesItss_EtsiTs102941DataContent_PR present;
	union EtsiTs102941MessagesItss_EtsiTs102941DataContent_u {
		InnerEcRequestSignedForPop_t	 enrolmentRequest;
		InnerEcResponse_t	 enrolmentResponse;
		InnerAtRequest_t	 authorizationRequest;
		InnerAtResponse_t	 authorizationResponse;
		ToBeSignedCrl_t	 certificateRevocationList;
		ToBeSignedTlmCtl_t	 certificateTrustListTlm;
		ToBeSignedRcaCtl_t	 certificateTrustListRca;
		NULL_t	 authorizationValidationRequest;
		NULL_t	 authorizationValidationResponse;
		NULL_t	 caCertificateRequest;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		ToBeSignedLinkCertificateTlm_t	 linkCertificateTlm;
		NULL_t	 singleSignedLinkCertificateRca;
		NULL_t	 doubleSignedlinkCertificateRca;
		struct EtsiTs102941MessagesItss_EtsiTs102941DataContent__ext1 {
			EeRaCertRequest_t	 butterflyAuthorizationRequest;
			EtsiTs102941ButterflyAuthorizationRequest_X509Signed_t	 x509SignedbutterflyAuthorizationRequest;
			RaEeCertInfo_t	 butterflyAuthorizationResponse;
			NULL_t	 butterflyCertificateRequest;
			NULL_t	 butterflyCertificateResponse;
			EeRaDownloadRequest_t	 butterflyAtDownloadRequest;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *ext1;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EtsiTs102941MessagesItss_EtsiTs102941DataContent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EtsiTs102941MessagesItss_EtsiTs102941DataContent;
extern asn_CHOICE_specifics_t asn_SPC_EtsiTs102941MessagesItss_EtsiTs102941DataContent_specs_1;
extern asn_TYPE_member_t asn_MBR_EtsiTs102941MessagesItss_EtsiTs102941DataContent_1[14];
extern asn_per_constraints_t asn_PER_type_EtsiTs102941MessagesItss_EtsiTs102941DataContent_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _EtsiTs102941MessagesItss_EtsiTs102941DataContent_H_ */
#include "asn_internal.h"
