/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "ASNfiles/ETSI CAM v1.4.1enh.asn"
 */

#ifndef	_GPULoad_H_
#define	_GPULoad_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GPULoad {
	GPULoad_zeroUsage	= 0,
	GPULoad_halfUsage	= 5000,
	GPULoad_fullUsage	= 10000,
	GPULoad_unavailable	= 10001
} e_GPULoad;

/* GPULoad */
typedef long	 GPULoad_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_GPULoad_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_GPULoad;
asn_struct_free_f GPULoad_free;
asn_struct_print_f GPULoad_print;
asn_constr_check_f GPULoad_constraint;
ber_type_decoder_f GPULoad_decode_ber;
der_type_encoder_f GPULoad_encode_der;
xer_type_decoder_f GPULoad_decode_xer;
xer_type_encoder_f GPULoad_encode_xer;
oer_type_decoder_f GPULoad_decode_oer;
oer_type_encoder_f GPULoad_encode_oer;
per_type_decoder_f GPULoad_decode_uper;
per_type_encoder_f GPULoad_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _GPULoad_H_ */
#include "asn_internal.h"
