/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_KinematicsCharacteristics_H_
#define	_KinematicsCharacteristics_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* KinematicsCharacteristics */
typedef NULL_t	 KinematicsCharacteristics_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_KinematicsCharacteristics;
asn_struct_free_f KinematicsCharacteristics_free;
asn_struct_print_f KinematicsCharacteristics_print;
asn_constr_check_f KinematicsCharacteristics_constraint;
ber_type_decoder_f KinematicsCharacteristics_decode_ber;
der_type_encoder_f KinematicsCharacteristics_encode_der;
xer_type_decoder_f KinematicsCharacteristics_decode_xer;
xer_type_encoder_f KinematicsCharacteristics_encode_xer;
jer_type_encoder_f KinematicsCharacteristics_encode_jer;
oer_type_decoder_f KinematicsCharacteristics_decode_oer;
oer_type_encoder_f KinematicsCharacteristics_encode_oer;
per_type_decoder_f KinematicsCharacteristics_decode_uper;
per_type_encoder_f KinematicsCharacteristics_encode_uper;
per_type_decoder_f KinematicsCharacteristics_decode_aper;
per_type_encoder_f KinematicsCharacteristics_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _KinematicsCharacteristics_H_ */
#include "asn_internal.h"
