/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1LaRaInterface"
 * 	found in "Ieee1609Dot2Dot1LaRaInterface.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_LaRaInterfacePdu_H_
#define	_LaRaInterfacePdu_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* LaRaInterfacePdu */
typedef NULL_t	 LaRaInterfacePdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LaRaInterfacePdu;
asn_struct_free_f LaRaInterfacePdu_free;
asn_struct_print_f LaRaInterfacePdu_print;
asn_constr_check_f LaRaInterfacePdu_constraint;
ber_type_decoder_f LaRaInterfacePdu_decode_ber;
der_type_encoder_f LaRaInterfacePdu_encode_der;
xer_type_decoder_f LaRaInterfacePdu_decode_xer;
xer_type_encoder_f LaRaInterfacePdu_encode_xer;
jer_type_encoder_f LaRaInterfacePdu_encode_jer;
oer_type_decoder_f LaRaInterfacePdu_decode_oer;
oer_type_encoder_f LaRaInterfacePdu_encode_oer;
per_type_decoder_f LaRaInterfacePdu_decode_uper;
per_type_encoder_f LaRaInterfacePdu_encode_uper;
per_type_decoder_f LaRaInterfacePdu_decode_aper;
per_type_encoder_f LaRaInterfacePdu_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LaRaInterfacePdu_H_ */
#include "asn_internal.h"
