/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_ManoeuvreCooperationGoal_H_
#define	_ManoeuvreCooperationGoal_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ManoeuvreCooperationGoal {
	ManoeuvreCooperationGoal_vehicleInterception	= 0,
	ManoeuvreCooperationGoal_roadSafety	= 1,
	ManoeuvreCooperationGoal_humanHelth	= 2,
	ManoeuvreCooperationGoal_emergencyIntervention	= 3,
	ManoeuvreCooperationGoal_roadOperatorIntervention	= 4,
	ManoeuvreCooperationGoal_localTrafficManagement	= 5,
	ManoeuvreCooperationGoal_globalTrafficManagement	= 6
} e_ManoeuvreCooperationGoal;

/* ManoeuvreCooperationGoal */
typedef long	 ManoeuvreCooperationGoal_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ManoeuvreCooperationGoal_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ManoeuvreCooperationGoal;
extern const asn_INTEGER_specifics_t asn_SPC_ManoeuvreCooperationGoal_specs_1;
asn_struct_free_f ManoeuvreCooperationGoal_free;
asn_struct_print_f ManoeuvreCooperationGoal_print;
asn_constr_check_f ManoeuvreCooperationGoal_constraint;
ber_type_decoder_f ManoeuvreCooperationGoal_decode_ber;
der_type_encoder_f ManoeuvreCooperationGoal_encode_der;
xer_type_decoder_f ManoeuvreCooperationGoal_decode_xer;
xer_type_encoder_f ManoeuvreCooperationGoal_encode_xer;
jer_type_encoder_f ManoeuvreCooperationGoal_encode_jer;
oer_type_decoder_f ManoeuvreCooperationGoal_decode_oer;
oer_type_encoder_f ManoeuvreCooperationGoal_encode_oer;
per_type_decoder_f ManoeuvreCooperationGoal_decode_uper;
per_type_encoder_f ManoeuvreCooperationGoal_encode_uper;
per_type_decoder_f ManoeuvreCooperationGoal_decode_aper;
per_type_encoder_f ManoeuvreCooperationGoal_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ManoeuvreCooperationGoal_H_ */
#include "asn_internal.h"
