/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_ManoeuvreId_H_
#define	_ManoeuvreId_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Identifier1B.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ManoeuvreId */
typedef Identifier1B_t	 ManoeuvreId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ManoeuvreId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ManoeuvreId;
asn_struct_free_f ManoeuvreId_free;
asn_struct_print_f ManoeuvreId_print;
asn_constr_check_f ManoeuvreId_constraint;
ber_type_decoder_f ManoeuvreId_decode_ber;
der_type_encoder_f ManoeuvreId_encode_der;
xer_type_decoder_f ManoeuvreId_decode_xer;
xer_type_encoder_f ManoeuvreId_encode_xer;
jer_type_encoder_f ManoeuvreId_encode_jer;
oer_type_decoder_f ManoeuvreId_decode_oer;
oer_type_encoder_f ManoeuvreId_encode_oer;
per_type_decoder_f ManoeuvreId_decode_uper;
per_type_encoder_f ManoeuvreId_encode_uper;
per_type_decoder_f ManoeuvreId_decode_aper;
per_type_encoder_f ManoeuvreId_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ManoeuvreId_H_ */
#include "asn_internal.h"
