/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_ManoeuvreOverallStrategy_H_
#define	_ManoeuvreOverallStrategy_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"
#include "NativeInteger.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ManoeuvreOverallStrategy_PR {
	ManoeuvreOverallStrategy_PR_NOTHING,	/* No components present */
	ManoeuvreOverallStrategy_PR_undefined,
	ManoeuvreOverallStrategy_PR_transitToHumanDrivenMode,
	ManoeuvreOverallStrategy_PR_transitToAutomatedDrivingMode,
	ManoeuvreOverallStrategy_PR_driveStraight,
	ManoeuvreOverallStrategy_PR_turnLeft,
	ManoeuvreOverallStrategy_PR_turnRight,
	ManoeuvreOverallStrategy_PR_uTurn,
	ManoeuvreOverallStrategy_PR_moveBackward,
	ManoeuvreOverallStrategy_PR_overtake,
	ManoeuvreOverallStrategy_PR_accelerate,
	ManoeuvreOverallStrategy_PR_slowdown,
	ManoeuvreOverallStrategy_PR_stop,
	ManoeuvreOverallStrategy_PR_goToLeftLane,
	ManoeuvreOverallStrategy_PR_oToRightLane,
	ManoeuvreOverallStrategy_PR_getOnHighway,
	ManoeuvreOverallStrategy_PR_exitHighway,
	ManoeuvreOverallStrategy_PR_takeTollingLane,
	ManoeuvreOverallStrategy_PR_stopAndWait,
	ManoeuvreOverallStrategy_PR_emergencyBrakeAndStop,
	ManoeuvreOverallStrategy_PR_resetStopAndRestartMoving,
	ManoeuvreOverallStrategy_PR_stayInLane,
	ManoeuvreOverallStrategy_PR_resetStayInLane,
	ManoeuvreOverallStrategy_PR_stayAway,
	ManoeuvreOverallStrategy_PR_resetStayAway,
	ManoeuvreOverallStrategy_PR_followMe,
	ManoeuvreOverallStrategy_PR_existingGroup,
	ManoeuvreOverallStrategy_PR_temporarilyDisbandAnExistingGroup,
	ManoeuvreOverallStrategy_PR_constituteAtemporarilyGroup,
	ManoeuvreOverallStrategy_PR_disbandATemporarilyGroup
} ManoeuvreOverallStrategy_PR;

/* ManoeuvreOverallStrategy */
typedef struct ManoeuvreOverallStrategy {
	ManoeuvreOverallStrategy_PR present;
	union ManoeuvreOverallStrategy_u {
		NULL_t	 undefined;
		NULL_t	 transitToHumanDrivenMode;
		NULL_t	 transitToAutomatedDrivingMode;
		NULL_t	 driveStraight;
		NULL_t	 turnLeft;
		NULL_t	 turnRight;
		NULL_t	 uTurn;
		NULL_t	 moveBackward;
		NULL_t	 overtake;
		NULL_t	 accelerate;
		NULL_t	 slowdown;
		NULL_t	 stop;
		NULL_t	 goToLeftLane;
		NULL_t	 oToRightLane;
		NULL_t	 getOnHighway;
		NULL_t	 exitHighway;
		long	 takeTollingLane;
		NULL_t	 stopAndWait;
		NULL_t	 emergencyBrakeAndStop;
		NULL_t	 resetStopAndRestartMoving;
		NULL_t	 stayInLane;
		NULL_t	 resetStayInLane;
		NULL_t	 stayAway;
		NULL_t	 resetStayAway;
		NULL_t	 followMe;
		NULL_t	 existingGroup;
		NULL_t	 temporarilyDisbandAnExistingGroup;
		NULL_t	 constituteAtemporarilyGroup;
		NULL_t	 disbandATemporarilyGroup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ManoeuvreOverallStrategy_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ManoeuvreOverallStrategy;
extern asn_CHOICE_specifics_t asn_SPC_ManoeuvreOverallStrategy_specs_1;
extern asn_TYPE_member_t asn_MBR_ManoeuvreOverallStrategy_1[29];
extern asn_per_constraints_t asn_PER_type_ManoeuvreOverallStrategy_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ManoeuvreOverallStrategy_H_ */
#include "asn_internal.h"
