/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_ManoeuvreExecutionStatus_H_
#define	_ManoeuvreExecutionStatus_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ManoeuvreExecutionStatus {
	ManoeuvreExecutionStatus_started	= 0,
	ManoeuvreExecutionStatus_inProgress	= 1,
	ManoeuvreExecutionStatus_completed	= 2,
	ManoeuvreExecutionStatus_terminated	= 3,
	ManoeuvreExecutionStatus_chained	= 4
} e_ManoeuvreExecutionStatus;

/* ManoeuvreExecutionStatus */
typedef long	 ManoeuvreExecutionStatus_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ManoeuvreExecutionStatus_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ManoeuvreExecutionStatus;
extern const asn_INTEGER_specifics_t asn_SPC_ManoeuvreExecutionStatus_specs_1;
asn_struct_free_f ManoeuvreExecutionStatus_free;
asn_struct_print_f ManoeuvreExecutionStatus_print;
asn_constr_check_f ManoeuvreExecutionStatus_constraint;
ber_type_decoder_f ManoeuvreExecutionStatus_decode_ber;
der_type_encoder_f ManoeuvreExecutionStatus_encode_der;
xer_type_decoder_f ManoeuvreExecutionStatus_decode_xer;
xer_type_encoder_f ManoeuvreExecutionStatus_encode_xer;
jer_type_encoder_f ManoeuvreExecutionStatus_encode_jer;
oer_type_decoder_f ManoeuvreExecutionStatus_decode_oer;
oer_type_encoder_f ManoeuvreExecutionStatus_encode_oer;
per_type_decoder_f ManoeuvreExecutionStatus_decode_uper;
per_type_encoder_f ManoeuvreExecutionStatus_encode_uper;
per_type_decoder_f ManoeuvreExecutionStatus_decode_aper;
per_type_encoder_f ManoeuvreExecutionStatus_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ManoeuvreExecutionStatus_H_ */
#include "asn_internal.h"
