/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_ManoeuvreAdvice_H_
#define	_ManoeuvreAdvice_H_


#include "asn_application.h"

/* Including external dependencies */
#include "StationID.h"
#include "Submanoeuvres.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CurrentStateAdvisedChange;

/* ManoeuvreAdvice */
typedef struct ManoeuvreAdvice {
	StationId_t	 executantID;
	struct CurrentStateAdvisedChange	*currentStateAdvisedChange;	/* OPTIONAL */
	Submanoeuvres_t	 submaneuvres;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ManoeuvreAdvice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ManoeuvreAdvice;
extern asn_SEQUENCE_specifics_t asn_SPC_ManoeuvreAdvice_specs_1;
extern asn_TYPE_member_t asn_MBR_ManoeuvreAdvice_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CurrentStateAdvisedChange.h"

#endif	/* _ManoeuvreAdvice_H_ */
#include "asn_internal.h"
