/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_ManouevreResponse_H_
#define	_ManouevreResponse_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ManouevreResponse {
	ManouevreResponse_accept	= 0,
	ManouevreResponse_decline	= 1
} e_ManouevreResponse;

/* ManouevreResponse */
typedef long	 ManouevreResponse_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ManouevreResponse_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ManouevreResponse;
extern const asn_INTEGER_specifics_t asn_SPC_ManouevreResponse_specs_1;
asn_struct_free_f ManouevreResponse_free;
asn_struct_print_f ManouevreResponse_print;
asn_constr_check_f ManouevreResponse_constraint;
ber_type_decoder_f ManouevreResponse_decode_ber;
der_type_encoder_f ManouevreResponse_encode_der;
xer_type_decoder_f ManouevreResponse_decode_xer;
xer_type_encoder_f ManouevreResponse_encode_xer;
jer_type_encoder_f ManouevreResponse_encode_jer;
oer_type_decoder_f ManouevreResponse_decode_oer;
oer_type_encoder_f ManouevreResponse_encode_oer;
per_type_decoder_f ManouevreResponse_decode_uper;
per_type_encoder_f ManouevreResponse_encode_uper;
per_type_decoder_f ManouevreResponse_decode_aper;
per_type_encoder_f ManouevreResponse_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ManouevreResponse_H_ */
#include "asn_internal.h"
