/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_ManoeuvreCooperationCost_H_
#define	_ManoeuvreCooperationCost_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ManoeuvreCooperationCost {
	ManoeuvreCooperationCost_zero	= 0,
	ManoeuvreCooperationCost_oneThousndth	= 1
} e_ManoeuvreCooperationCost;

/* ManoeuvreCooperationCost */
typedef long	 ManoeuvreCooperationCost_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ManoeuvreCooperationCost_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ManoeuvreCooperationCost;
asn_struct_free_f ManoeuvreCooperationCost_free;
asn_struct_print_f ManoeuvreCooperationCost_print;
asn_constr_check_f ManoeuvreCooperationCost_constraint;
ber_type_decoder_f ManoeuvreCooperationCost_decode_ber;
der_type_encoder_f ManoeuvreCooperationCost_encode_der;
xer_type_decoder_f ManoeuvreCooperationCost_decode_xer;
xer_type_encoder_f ManoeuvreCooperationCost_encode_xer;
jer_type_encoder_f ManoeuvreCooperationCost_encode_jer;
oer_type_decoder_f ManoeuvreCooperationCost_decode_oer;
oer_type_encoder_f ManoeuvreCooperationCost_encode_oer;
per_type_decoder_f ManoeuvreCooperationCost_decode_uper;
per_type_encoder_f ManoeuvreCooperationCost_encode_uper;
per_type_decoder_f ManoeuvreCooperationCost_decode_aper;
per_type_encoder_f ManoeuvreCooperationCost_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ManoeuvreCooperationCost_H_ */
#include "asn_internal.h"
