/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_ManoeuvreAdviceContainer_H_
#define	_ManoeuvreAdviceContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ManoeuvreAdvice;

/* ManoeuvreAdviceContainer */
typedef struct ManoeuvreAdviceContainer {
	A_SEQUENCE_OF(struct ManoeuvreAdvice) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ManoeuvreAdviceContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ManoeuvreAdviceContainer;
extern asn_SET_OF_specifics_t asn_SPC_ManoeuvreAdviceContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_ManoeuvreAdviceContainer_1[1];
extern asn_per_constraints_t asn_PER_type_ManoeuvreAdviceContainer_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ManoeuvreAdvice.h"

#endif	/* _ManoeuvreAdviceContainer_H_ */
#include "asn_internal.h"
