/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_ManoeuvreCoordinationRational_H_
#define	_ManoeuvreCoordinationRational_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ManoeuvreCooperationGoal.h"
#include "ManoeuvreCooperationCost.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ManoeuvreCoordinationRational_PR {
	ManoeuvreCoordinationRational_PR_NOTHING,	/* No components present */
	ManoeuvreCoordinationRational_PR_manoeuvreCooperationGoal,
	ManoeuvreCoordinationRational_PR_manoeuvreCooperationCost
} ManoeuvreCoordinationRational_PR;

/* ManoeuvreCoordinationRational */
typedef struct ManoeuvreCoordinationRational {
	ManoeuvreCoordinationRational_PR present;
	union ManoeuvreCoordinationRational_u {
		ManoeuvreCooperationGoal_t	 manoeuvreCooperationGoal;
		ManoeuvreCooperationCost_t	 manoeuvreCooperationCost;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ManoeuvreCoordinationRational_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ManoeuvreCoordinationRational;
extern asn_CHOICE_specifics_t asn_SPC_ManoeuvreCoordinationRational_specs_1;
extern asn_TYPE_member_t asn_MBR_ManoeuvreCoordinationRational_1[2];
extern asn_per_constraints_t asn_PER_type_ManoeuvreCoordinationRational_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ManoeuvreCoordinationRational_H_ */
#include "asn_internal.h"
