/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1MaRaInterface"
 * 	found in "Ieee1609Dot2Dot1MaRaInterface.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_MaRaInterfacePdu_H_
#define	_MaRaInterfacePdu_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MaRaInterfacePdu */
typedef NULL_t	 MaRaInterfacePdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MaRaInterfacePdu;
asn_struct_free_f MaRaInterfacePdu_free;
asn_struct_print_f MaRaInterfacePdu_print;
asn_constr_check_f MaRaInterfacePdu_constraint;
ber_type_decoder_f MaRaInterfacePdu_decode_ber;
der_type_encoder_f MaRaInterfacePdu_encode_der;
xer_type_decoder_f MaRaInterfacePdu_decode_xer;
xer_type_encoder_f MaRaInterfacePdu_encode_xer;
jer_type_encoder_f MaRaInterfacePdu_encode_jer;
oer_type_decoder_f MaRaInterfacePdu_decode_oer;
oer_type_encoder_f MaRaInterfacePdu_encode_oer;
per_type_decoder_f MaRaInterfacePdu_decode_uper;
per_type_encoder_f MaRaInterfacePdu_encode_uper;
per_type_decoder_f MaRaInterfacePdu_decode_aper;
per_type_encoder_f MaRaInterfacePdu_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _MaRaInterfacePdu_H_ */
#include "asn_internal.h"
