/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Protocol"
 * 	found in "Ieee1609Dot2Dot1Protocol.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_MaSsp_H_
#define	_MaSsp_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Uint8.h"
#include "SequenceOfPsid.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MaSsp */
typedef struct MaSsp {
	Uint8_t	 version;
	SequenceOfPsid_t	 relevantPsids;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MaSsp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MaSsp;
extern asn_SEQUENCE_specifics_t asn_SPC_MaSsp_specs_1;
extern asn_TYPE_member_t asn_MBR_MaSsp_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _MaSsp_H_ */
#include "asn_internal.h"
