/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_MCM_H_
#define	_MCM_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ItsPduHeader.h"
#include "WrappedMcmInformationBlocks.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MCM */
typedef struct MCM {
	ItsPduHeader_t	 header;
	WrappedMcmInformationBlocks_t	 payload;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MCM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MCM;

#ifdef __cplusplus
}
#endif

#endif	/* _MCM_H_ */
#include "asn_internal.h"
