/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_McmBasicContainer_H_
#define	_McmBasicContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TimestampIts.h"
#include "StationID.h"
#include "McmStationType.h"
#include "McmItssRole.h"
#include "ReferencePositionWithConfidence.h"
#include "McmType.h"
#include "ManoeuvreId.h"
#include "ManoeuvreCoordinationConcept.h"
#include "ManoeuvreExecutionStatus.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ManoeuvreCoordinationRational;

/* McmBasicContainer */
typedef struct McmBasicContainer {
	TimestampIts_t	 generationDeltaTime;
	StationId_t	 stationID;
	McmStationType_t	 stationType;
	McmItssRole_t	 itssRole;
	ReferencePositionWithConfidence_t	 position;
	McmType_t	 mcmType;
	ManoeuvreId_t	 manoeuvreId;
	ManoeuvreCoordinationConcept_t	 concept;
	struct ManoeuvreCoordinationRational	*rational;	/* OPTIONAL */
	ManoeuvreExecutionStatus_t	*executionStatus;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} McmBasicContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_McmBasicContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_McmBasicContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_McmBasicContainer_1[10];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ManoeuvreCoordinationRational.h"

#endif	/* _McmBasicContainer_H_ */
#include "asn_internal.h"
