/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_McmItssRole_H_
#define	_McmItssRole_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum McmItssRole {
	McmItssRole_notAvailable	= 0,
	McmItssRole_coordinatingItss	= 1,
	McmItssRole_notCoordinatingSubjectVehicle	= 2,
	McmItssRole_targetVehicle	= 3
	/*
	 * Enumeration is extensible
	 */
} e_McmItssRole;

/* McmItssRole */
typedef long	 McmItssRole_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_McmItssRole_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_McmItssRole;
extern const asn_INTEGER_specifics_t asn_SPC_McmItssRole_specs_1;
asn_struct_free_f McmItssRole_free;
asn_struct_print_f McmItssRole_print;
asn_constr_check_f McmItssRole_constraint;
ber_type_decoder_f McmItssRole_decode_ber;
der_type_encoder_f McmItssRole_encode_der;
xer_type_decoder_f McmItssRole_decode_xer;
xer_type_encoder_f McmItssRole_encode_xer;
jer_type_encoder_f McmItssRole_encode_jer;
oer_type_decoder_f McmItssRole_decode_oer;
oer_type_encoder_f McmItssRole_encode_oer;
per_type_decoder_f McmItssRole_decode_uper;
per_type_encoder_f McmItssRole_encode_uper;
per_type_decoder_f McmItssRole_decode_aper;
per_type_encoder_f McmItssRole_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _McmItssRole_H_ */
#include "asn_internal.h"
