/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_McmStationType_H_
#define	_McmStationType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum McmStationType {
	McmStationType_vruPortableDevice	= 0,
	McmStationType_vehicle	= 1,
	McmStationType_roadsideUnit	= 2,
	McmStationType_centralStation	= 3
	/*
	 * Enumeration is extensible
	 */
} e_McmStationType;

/* McmStationType */
typedef long	 McmStationType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_McmStationType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_McmStationType;
extern const asn_INTEGER_specifics_t asn_SPC_McmStationType_specs_1;
asn_struct_free_f McmStationType_free;
asn_struct_print_f McmStationType_print;
asn_constr_check_f McmStationType_constraint;
ber_type_decoder_f McmStationType_decode_ber;
der_type_encoder_f McmStationType_encode_der;
xer_type_decoder_f McmStationType_decode_xer;
xer_type_encoder_f McmStationType_encode_xer;
jer_type_encoder_f McmStationType_encode_jer;
oer_type_decoder_f McmStationType_decode_oer;
oer_type_encoder_f McmStationType_encode_oer;
per_type_decoder_f McmStationType_decode_uper;
per_type_encoder_f McmStationType_encode_uper;
per_type_decoder_f McmStationType_decode_aper;
per_type_encoder_f McmStationType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _McmStationType_H_ */
#include "asn_internal.h"
