/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Protocol"
 * 	found in "Ieee1609Dot2Dot1Protocol.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_MultiSignedCtlSpdu_H_
#define	_MultiSignedCtlSpdu_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Ieee1609Dot2Data-Unsecured.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MultiSignedCtlSpdu */
typedef Ieee1609Dot2Data_Unsecured_232P0_t	 MultiSignedCtlSpdu_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MultiSignedCtlSpdu_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MultiSignedCtlSpdu;
asn_struct_free_f MultiSignedCtlSpdu_free;
asn_struct_print_f MultiSignedCtlSpdu_print;
asn_constr_check_f MultiSignedCtlSpdu_constraint;
ber_type_decoder_f MultiSignedCtlSpdu_decode_ber;
der_type_encoder_f MultiSignedCtlSpdu_encode_der;
xer_type_decoder_f MultiSignedCtlSpdu_decode_xer;
xer_type_encoder_f MultiSignedCtlSpdu_encode_xer;
jer_type_encoder_f MultiSignedCtlSpdu_encode_jer;
oer_type_decoder_f MultiSignedCtlSpdu_decode_oer;
oer_type_encoder_f MultiSignedCtlSpdu_encode_oer;
per_type_decoder_f MultiSignedCtlSpdu_decode_uper;
per_type_encoder_f MultiSignedCtlSpdu_encode_uper;
per_type_decoder_f MultiSignedCtlSpdu_decode_aper;
per_type_encoder_f MultiSignedCtlSpdu_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _MultiSignedCtlSpdu_H_ */
#include "asn_internal.h"
