/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Protocol"
 * 	found in "Ieee1609Dot2Dot1Protocol.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_RaEeEnrollmentCertAckSpdu_H_
#define	_RaEeEnrollmentCertAckSpdu_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Ieee1609Dot2Data-Signed.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RaEeEnrollmentCertAckSpdu */
typedef Ieee1609Dot2Data_Signed_246P2_t	 RaEeEnrollmentCertAckSpdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RaEeEnrollmentCertAckSpdu;
asn_struct_free_f RaEeEnrollmentCertAckSpdu_free;
asn_struct_print_f RaEeEnrollmentCertAckSpdu_print;
asn_constr_check_f RaEeEnrollmentCertAckSpdu_constraint;
ber_type_decoder_f RaEeEnrollmentCertAckSpdu_decode_ber;
der_type_encoder_f RaEeEnrollmentCertAckSpdu_encode_der;
xer_type_decoder_f RaEeEnrollmentCertAckSpdu_decode_xer;
xer_type_encoder_f RaEeEnrollmentCertAckSpdu_encode_xer;
jer_type_encoder_f RaEeEnrollmentCertAckSpdu_encode_jer;
oer_type_decoder_f RaEeEnrollmentCertAckSpdu_decode_oer;
oer_type_encoder_f RaEeEnrollmentCertAckSpdu_encode_oer;
per_type_decoder_f RaEeEnrollmentCertAckSpdu_decode_uper;
per_type_encoder_f RaEeEnrollmentCertAckSpdu_encode_uper;
per_type_decoder_f RaEeEnrollmentCertAckSpdu_decode_aper;
per_type_encoder_f RaEeEnrollmentCertAckSpdu_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RaEeEnrollmentCertAckSpdu_H_ */
#include "asn_internal.h"
