/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "./ASNfiles/ETSI CAM v1.4.1enh.asn"
 */

#ifndef	_RAMLoad_H_
#define	_RAMLoad_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RAMLoad {
	RAMLoad_maximumAllowedValue	= 512000,
	RAMLoad_unavailable	= 512001
} e_RAMLoad;

/* RAMLoad */
typedef long	 RAMLoad_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RAMLoad_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RAMLoad;
asn_struct_free_f RAMLoad_free;
asn_struct_print_f RAMLoad_print;
asn_constr_check_f RAMLoad_constraint;
ber_type_decoder_f RAMLoad_decode_ber;
der_type_encoder_f RAMLoad_encode_der;
xer_type_decoder_f RAMLoad_decode_xer;
xer_type_encoder_f RAMLoad_encode_xer;
oer_type_decoder_f RAMLoad_decode_oer;
oer_type_encoder_f RAMLoad_encode_oer;
per_type_decoder_f RAMLoad_decode_uper;
per_type_encoder_f RAMLoad_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RAMLoad_H_ */
#include "asn_internal.h"
