/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941MessagesCa"
 * 	found in "EtsiTs102941MessagesCa.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_RcaDoubleSignedLinkCertificateMessage_H_
#define	_RcaDoubleSignedLinkCertificateMessage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "EtsiTs103097Data-Signed.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RcaDoubleSignedLinkCertificateMessage */
typedef EtsiTs103097Data_Signed_63P0_t	 RcaDoubleSignedLinkCertificateMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RcaDoubleSignedLinkCertificateMessage;
asn_struct_free_f RcaDoubleSignedLinkCertificateMessage_free;
asn_struct_print_f RcaDoubleSignedLinkCertificateMessage_print;
asn_constr_check_f RcaDoubleSignedLinkCertificateMessage_constraint;
ber_type_decoder_f RcaDoubleSignedLinkCertificateMessage_decode_ber;
der_type_encoder_f RcaDoubleSignedLinkCertificateMessage_encode_der;
xer_type_decoder_f RcaDoubleSignedLinkCertificateMessage_decode_xer;
xer_type_encoder_f RcaDoubleSignedLinkCertificateMessage_encode_xer;
jer_type_encoder_f RcaDoubleSignedLinkCertificateMessage_encode_jer;
oer_type_decoder_f RcaDoubleSignedLinkCertificateMessage_decode_oer;
oer_type_encoder_f RcaDoubleSignedLinkCertificateMessage_encode_oer;
per_type_decoder_f RcaDoubleSignedLinkCertificateMessage_decode_uper;
per_type_encoder_f RcaDoubleSignedLinkCertificateMessage_encode_uper;
per_type_decoder_f RcaDoubleSignedLinkCertificateMessage_decode_aper;
per_type_encoder_f RcaDoubleSignedLinkCertificateMessage_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RcaDoubleSignedLinkCertificateMessage_H_ */
#include "asn_internal.h"
