/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_ResponseContainer_H_
#define	_ResponseContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ManouevreResponse.h"
#include "DeclineReason.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ListOfSubmanoeuvreDescriptionsContainer;

/* ResponseContainer */
typedef struct ResponseContainer {
	ManouevreResponse_t	 manouevreResponse;
	DeclineReason_t	*declineReason;	/* OPTIONAL */
	struct ListOfSubmanoeuvreDescriptionsContainer	*submaneuvres;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResponseContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResponseContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_ResponseContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_ResponseContainer_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ListOfSubmanoeuvreDescriptionsContainer.h"

#endif	/* _ResponseContainer_H_ */
#include "asn_internal.h"
