/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_RLLC_H_
#define	_RLLC_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RLLC {
	RLLC_currentLane	= 0
} e_RLLC;

/* RLLC */
typedef BIT_STRING_t	 RLLC_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RLLC;
asn_struct_free_f RLLC_free;
asn_struct_print_f RLLC_print;
asn_constr_check_f RLLC_constraint;
ber_type_decoder_f RLLC_decode_ber;
der_type_encoder_f RLLC_encode_der;
xer_type_decoder_f RLLC_decode_xer;
xer_type_encoder_f RLLC_encode_xer;
jer_type_encoder_f RLLC_encode_jer;
oer_type_decoder_f RLLC_decode_oer;
oer_type_encoder_f RLLC_encode_oer;
per_type_decoder_f RLLC_decode_uper;
per_type_encoder_f RLLC_encode_uper;
per_type_decoder_f RLLC_decode_aper;
per_type_encoder_f RLLC_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RLLC_H_ */
#include "asn_internal.h"
