/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_RRLC_H_
#define	_RRLC_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRLC {
	RRLC_currentLane	= 0
} e_RRLC;

/* RRLC */
typedef BIT_STRING_t	 RRLC_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRLC;
asn_struct_free_f RRLC_free;
asn_struct_print_f RRLC_print;
asn_constr_check_f RRLC_constraint;
ber_type_decoder_f RRLC_decode_ber;
der_type_encoder_f RRLC_encode_der;
xer_type_decoder_f RRLC_decode_xer;
xer_type_encoder_f RRLC_encode_xer;
jer_type_encoder_f RRLC_encode_jer;
oer_type_decoder_f RRLC_decode_oer;
oer_type_encoder_f RRLC_encode_oer;
per_type_decoder_f RRLC_decode_uper;
per_type_encoder_f RRLC_encode_uper;
per_type_decoder_f RRLC_decode_aper;
per_type_encoder_f RRLC_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RRLC_H_ */
#include "asn_internal.h"
