/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Protocol"
 * 	found in "Ieee1609Dot2Dot1Protocol.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_ScmsPdu_EeEcaCertRequest_H_
#define	_ScmsPdu_EeEcaCertRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ScmsPdu-Scoped.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ScmsPdu-EeEcaCertRequest */
typedef ScmsPdu_Scoped_219P1_t	 ScmsPdu_EeEcaCertRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ScmsPdu_EeEcaCertRequest;
asn_struct_free_f ScmsPdu_EeEcaCertRequest_free;
asn_struct_print_f ScmsPdu_EeEcaCertRequest_print;
asn_constr_check_f ScmsPdu_EeEcaCertRequest_constraint;
ber_type_decoder_f ScmsPdu_EeEcaCertRequest_decode_ber;
der_type_encoder_f ScmsPdu_EeEcaCertRequest_encode_der;
xer_type_decoder_f ScmsPdu_EeEcaCertRequest_decode_xer;
xer_type_encoder_f ScmsPdu_EeEcaCertRequest_encode_xer;
jer_type_encoder_f ScmsPdu_EeEcaCertRequest_encode_jer;
oer_type_decoder_f ScmsPdu_EeEcaCertRequest_decode_oer;
oer_type_encoder_f ScmsPdu_EeEcaCertRequest_encode_oer;
per_type_decoder_f ScmsPdu_EeEcaCertRequest_decode_uper;
per_type_encoder_f ScmsPdu_EeEcaCertRequest_encode_uper;
per_type_decoder_f ScmsPdu_EeEcaCertRequest_decode_aper;
per_type_encoder_f ScmsPdu_EeEcaCertRequest_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ScmsPdu_EeEcaCertRequest_H_ */
#include "asn_internal.h"
