/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Protocol"
 * 	found in "Ieee1609Dot2Dot1Protocol.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_ScmsPdu_H_
#define	_ScmsPdu_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Uint8.h"
#include "AcaEeInterfacePdu.h"
#include "AcaLaInterfacePdu.h"
#include "AcaMaInterfacePdu.h"
#include "AcaRaInterfacePdu.h"
#include "CertManagementPdu.h"
#include "EcaEeInterfacePdu.h"
#include "EeMaInterfacePdu.h"
#include "EeRaInterfacePdu.h"
#include "LaMaInterfacePdu.h"
#include "LaRaInterfacePdu.h"
#include "MaRaInterfacePdu.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ScmsPdu__content_PR {
	ScmsPdu__content_PR_NOTHING,	/* No components present */
	ScmsPdu__content_PR_aca_ee,
	ScmsPdu__content_PR_aca_la,
	ScmsPdu__content_PR_aca_ma,
	ScmsPdu__content_PR_aca_ra,
	ScmsPdu__content_PR_cert,
	ScmsPdu__content_PR_eca_ee,
	ScmsPdu__content_PR_ee_ma,
	ScmsPdu__content_PR_ee_ra,
	ScmsPdu__content_PR_la_ma,
	ScmsPdu__content_PR_la_ra,
	ScmsPdu__content_PR_ma_ra
	/* Extensions may appear below */
	
} ScmsPdu__content_PR;

/* ScmsPdu */
typedef struct ScmsPdu {
	Uint8_t	 version;
	struct ScmsPdu__content {
		ScmsPdu__content_PR present;
		union ScmsPdu__content_u {
			AcaEeInterfacePdu_t	 aca_ee;
			AcaLaInterfacePdu_t	 aca_la;
			AcaMaInterfacePdu_t	 aca_ma;
			AcaRaInterfacePdu_t	 aca_ra;
			CertManagementPdu_t	 cert;
			EcaEeInterfacePdu_t	 eca_ee;
			EeMaInterfacePdu_t	 ee_ma;
			EeRaInterfacePdu_t	 ee_ra;
			LaMaInterfacePdu_t	 la_ma;
			LaRaInterfacePdu_t	 la_ra;
			MaRaInterfacePdu_t	 ma_ra;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} content;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ScmsPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ScmsPdu;
extern asn_SEQUENCE_specifics_t asn_SPC_ScmsPdu_specs_1;
extern asn_TYPE_member_t asn_MBR_ScmsPdu_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ScmsPdu_H_ */
#include "asn_internal.h"
