/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Protocol"
 * 	found in "Ieee1609Dot2Dot1Protocol.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_SignedCertificateRequest_H_
#define	_SignedCertificateRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "HashAlgorithm.h"
#include "ScopedCertificateRequest.h"
#include "SignerIdentifier.h"
#include "Signature.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SignedCertificateRequest */
typedef struct SignedCertificateRequest {
	HashAlgorithm_t	 hashAlgorithmId;
	ScopedCertificateRequest_t	 tbsRequest;
	SignerIdentifier_t	 signer;
	Signature_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignedCertificateRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignedCertificateRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _SignedCertificateRequest_H_ */
#include "asn_internal.h"
