/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_SubmanoeuvreStrategy_H_
#define	_SubmanoeuvreStrategy_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"
#include "NativeInteger.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SubmanoeuvreStrategy_PR {
	SubmanoeuvreStrategy_PR_NOTHING,	/* No components present */
	SubmanoeuvreStrategy_PR_undefined,
	SubmanoeuvreStrategy_PR_transitToHumanDrivenMode,
	SubmanoeuvreStrategy_PR_transitToAutomatedDrivingMode,
	SubmanoeuvreStrategy_PR_driveStraight,
	SubmanoeuvreStrategy_PR_turnLeft,
	SubmanoeuvreStrategy_PR_turnRight,
	SubmanoeuvreStrategy_PR_uTurn,
	SubmanoeuvreStrategy_PR_moveBackward,
	SubmanoeuvreStrategy_PR_overtake,
	SubmanoeuvreStrategy_PR_accelerate,
	SubmanoeuvreStrategy_PR_slowDown,
	SubmanoeuvreStrategy_PR_stop,
	SubmanoeuvreStrategy_PR_goToLeftLane,
	SubmanoeuvreStrategy_PR_goToRightLane,
	SubmanoeuvreStrategy_PR_getOnHighway,
	SubmanoeuvreStrategy_PR_exitHighway,
	SubmanoeuvreStrategy_PR_takeTollingLane,
	SubmanoeuvreStrategy_PR_stopAndWait,
	SubmanoeuvreStrategy_PR_emergencyBrakeAndStop,
	SubmanoeuvreStrategy_PR_resetStopAndRestartMoving,
	SubmanoeuvreStrategy_PR_stayInLane,
	SubmanoeuvreStrategy_PR_resetStayInLane,
	SubmanoeuvreStrategy_PR_stayAway,
	SubmanoeuvreStrategy_PR_resetStayAway,
	SubmanoeuvreStrategy_PR_followMe,
	SubmanoeuvreStrategy_PR_existingGroup,
	SubmanoeuvreStrategy_PR_temporarilyDisbandAnExistingGroup,
	SubmanoeuvreStrategy_PR_constituteATemporarilyGroup,
	SubmanoeuvreStrategy_PR_disbandATemporarilyGroup
} SubmanoeuvreStrategy_PR;

/* SubmanoeuvreStrategy */
typedef struct SubmanoeuvreStrategy {
	SubmanoeuvreStrategy_PR present;
	union SubmanoeuvreStrategy_u {
		NULL_t	 undefined;
		NULL_t	 transitToHumanDrivenMode;
		NULL_t	 transitToAutomatedDrivingMode;
		NULL_t	 driveStraight;
		NULL_t	 turnLeft;
		NULL_t	 turnRight;
		NULL_t	 uTurn;
		NULL_t	 moveBackward;
		NULL_t	 overtake;
		NULL_t	 accelerate;
		NULL_t	 slowDown;
		NULL_t	 stop;
		NULL_t	 goToLeftLane;
		NULL_t	 goToRightLane;
		NULL_t	 getOnHighway;
		NULL_t	 exitHighway;
		long	 takeTollingLane;
		NULL_t	 stopAndWait;
		NULL_t	 emergencyBrakeAndStop;
		NULL_t	 resetStopAndRestartMoving;
		NULL_t	 stayInLane;
		NULL_t	 resetStayInLane;
		NULL_t	 stayAway;
		NULL_t	 resetStayAway;
		NULL_t	 followMe;
		NULL_t	 existingGroup;
		NULL_t	 temporarilyDisbandAnExistingGroup;
		NULL_t	 constituteATemporarilyGroup;
		NULL_t	 disbandATemporarilyGroup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SubmanoeuvreStrategy_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SubmanoeuvreStrategy;
extern asn_CHOICE_specifics_t asn_SPC_SubmanoeuvreStrategy_specs_1;
extern asn_TYPE_member_t asn_MBR_SubmanoeuvreStrategy_1[29];
extern asn_per_constraints_t asn_PER_type_SubmanoeuvreStrategy_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SubmanoeuvreStrategy_H_ */
#include "asn_internal.h"
