/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_SubmanoeuvreDescription_H_
#define	_SubmanoeuvreDescription_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Identifier1B.h"
#include "TemporalCharacteristics.h"
#include "KinematicsCharacteristics.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SubmanoeuvreStrategy;
struct Trajectory;
struct TrrDescription;

/* SubmanoeuvreDescription */
typedef struct SubmanoeuvreDescription {
	Identifier1B_t	 submanoeuvreID;
	struct SubmanoeuvreStrategy	*submanoeuvreStrategy;	/* OPTIONAL */
	struct Trajectory	*referenceTrajectory;	/* OPTIONAL */
	struct TrrDescription	*targetRoadResourceIContainer;	/* OPTIONAL */
	TemporalCharacteristics_t	 temporalCharateristics;
	KinematicsCharacteristics_t	*kinematicsCharacteristics;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SubmanoeuvreDescription_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SubmanoeuvreDescription;
extern asn_SEQUENCE_specifics_t asn_SPC_SubmanoeuvreDescription_specs_1;
extern asn_TYPE_member_t asn_MBR_SubmanoeuvreDescription_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SubmanoeuvreStrategy.h"
#include "Trajectory.h"
#include "TrrDescription.h"

#endif	/* _SubmanoeuvreDescription_H_ */
#include "asn_internal.h"
