/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_Submanoeuvres_H_
#define	_Submanoeuvres_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Submanoeuvre;

/* Submanoeuvres */
typedef struct Submanoeuvres {
	A_SEQUENCE_OF(struct Submanoeuvre) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Submanoeuvres_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Submanoeuvres;
extern asn_SET_OF_specifics_t asn_SPC_Submanoeuvres_specs_1;
extern asn_TYPE_member_t asn_MBR_Submanoeuvres_1[1];
extern asn_per_constraints_t asn_PER_type_Submanoeuvres_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Submanoeuvre.h"

#endif	/* _Submanoeuvres_H_ */
#include "asn_internal.h"
