/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_TemporalCharacteristics_H_
#define	_TemporalCharacteristics_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TemporalCharacteristics */
typedef struct TemporalCharacteristics {
	long	 tRROccupancyStartTime;
	long	 tRROccupancyEndTime;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TemporalCharacteristics_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TemporalCharacteristics;
extern asn_SEQUENCE_specifics_t asn_SPC_TemporalCharacteristics_specs_1;
extern asn_TYPE_member_t asn_MBR_TemporalCharacteristics_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TemporalCharacteristics_H_ */
#include "asn_internal.h"
