/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941TypesLinkCertificate"
 * 	found in "EtsiTs102941TypesLinkCertificate.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_ToBeSignedLinkCertificateTlm_H_
#define	_ToBeSignedLinkCertificateTlm_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ToBeSignedLinkCertificate.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ToBeSignedLinkCertificateTlm */
typedef ToBeSignedLinkCertificate_t	 ToBeSignedLinkCertificateTlm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ToBeSignedLinkCertificateTlm;
asn_struct_free_f ToBeSignedLinkCertificateTlm_free;
asn_struct_print_f ToBeSignedLinkCertificateTlm_print;
asn_constr_check_f ToBeSignedLinkCertificateTlm_constraint;
ber_type_decoder_f ToBeSignedLinkCertificateTlm_decode_ber;
der_type_encoder_f ToBeSignedLinkCertificateTlm_encode_der;
xer_type_decoder_f ToBeSignedLinkCertificateTlm_decode_xer;
xer_type_encoder_f ToBeSignedLinkCertificateTlm_encode_xer;
jer_type_encoder_f ToBeSignedLinkCertificateTlm_encode_jer;
oer_type_decoder_f ToBeSignedLinkCertificateTlm_decode_oer;
oer_type_encoder_f ToBeSignedLinkCertificateTlm_encode_oer;
per_type_decoder_f ToBeSignedLinkCertificateTlm_decode_uper;
per_type_encoder_f ToBeSignedLinkCertificateTlm_encode_uper;
per_type_decoder_f ToBeSignedLinkCertificateTlm_decode_aper;
per_type_encoder_f ToBeSignedLinkCertificateTlm_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ToBeSignedLinkCertificateTlm_H_ */
#include "asn_internal.h"
