/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_TrrDescription_H_
#define	_TrrDescription_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TrrType.h"
#include "LaneCount.h"
#include "TRRWidth.h"
#include "TRRLength.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct WayPoint;
struct Wgs84Angle;

/* TrrDescription */
typedef struct TrrDescription {
	TrrType_t	 trrType;
	LaneCount_t	 laneCount;
	LaneCount_t	*startingLaneNumber;	/* OPTIONAL */
	LaneCount_t	*endingLaneNumber;	/* OPTIONAL */
	struct waypoints {
		A_SEQUENCE_OF(struct WayPoint) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *waypoints;
	struct heading {
		A_SEQUENCE_OF(struct Wgs84Angle) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *heading;
	TRRWidth_t	 trrWidth;
	TRRLength_t	 trrLength;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TrrDescription_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrrDescription;
extern asn_SEQUENCE_specifics_t asn_SPC_TrrDescription_specs_1;
extern asn_TYPE_member_t asn_MBR_TrrDescription_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "WayPoint.h"
#include "Wgs84Angle.h"

#endif	/* _TrrDescription_H_ */
#include "asn_internal.h"
