/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_TRRLength_H_
#define	_TRRLength_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TRRLength */
typedef long	 TRRLength_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TRRLength_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TRRLength;
asn_struct_free_f TRRLength_free;
asn_struct_print_f TRRLength_print;
asn_constr_check_f TRRLength_constraint;
ber_type_decoder_f TRRLength_decode_ber;
der_type_encoder_f TRRLength_encode_der;
xer_type_decoder_f TRRLength_decode_xer;
xer_type_encoder_f TRRLength_encode_xer;
jer_type_encoder_f TRRLength_encode_jer;
oer_type_decoder_f TRRLength_decode_oer;
oer_type_encoder_f TRRLength_encode_oer;
per_type_decoder_f TRRLength_decode_uper;
per_type_encoder_f TRRLength_encode_uper;
per_type_decoder_f TRRLength_decode_aper;
per_type_encoder_f TRRLength_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TRRLength_H_ */
#include "asn_internal.h"
