/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_TrrType_H_
#define	_TrrType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TrrType {
	TrrType_trrType1	= 0,
	TrrType_trrType2	= 1,
	TrrType_trrType3	= 2
} e_TrrType;

/* TrrType */
typedef long	 TrrType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TrrType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TrrType;
extern const asn_INTEGER_specifics_t asn_SPC_TrrType_specs_1;
asn_struct_free_f TrrType_free;
asn_struct_print_f TrrType_print;
asn_constr_check_f TrrType_constraint;
ber_type_decoder_f TrrType_decode_ber;
der_type_encoder_f TrrType_encode_der;
xer_type_decoder_f TrrType_decode_xer;
xer_type_encoder_f TrrType_encode_xer;
jer_type_encoder_f TrrType_encode_jer;
oer_type_decoder_f TrrType_decode_oer;
oer_type_encoder_f TrrType_encode_oer;
per_type_decoder_f TrrType_decode_uper;
per_type_encoder_f TrrType_encode_uper;
per_type_decoder_f TrrType_decode_aper;
per_type_encoder_f TrrType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TrrType_H_ */
#include "asn_internal.h"
