/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_TRRWidth_H_
#define	_TRRWidth_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TRRWidth */
typedef long	 TRRWidth_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TRRWidth_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TRRWidth;
asn_struct_free_f TRRWidth_free;
asn_struct_print_f TRRWidth_print;
asn_constr_check_f TRRWidth_constraint;
ber_type_decoder_f TRRWidth_decode_ber;
der_type_encoder_f TRRWidth_encode_der;
xer_type_decoder_f TRRWidth_decode_xer;
xer_type_encoder_f TRRWidth_encode_xer;
jer_type_encoder_f TRRWidth_encode_jer;
oer_type_decoder_f TRRWidth_decode_oer;
oer_type_encoder_f TRRWidth_encode_oer;
per_type_decoder_f TRRWidth_decode_uper;
per_type_encoder_f TRRWidth_encode_uper;
per_type_decoder_f TRRWidth_decode_aper;
per_type_encoder_f TRRWidth_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TRRWidth_H_ */
#include "asn_internal.h"
