/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Acpc"
 * 	found in "Ieee1609Dot2Dot1Acpc.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_pki/`
 */

#ifndef	_UnsecuredAprvBinaryTree_H_
#define	_UnsecuredAprvBinaryTree_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Ieee1609Dot2Data-Unsecured.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UnsecuredAprvBinaryTree */
typedef Ieee1609Dot2Data_Unsecured_232P1_t	 UnsecuredAprvBinaryTree_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UnsecuredAprvBinaryTree;
asn_struct_free_f UnsecuredAprvBinaryTree_free;
asn_struct_print_f UnsecuredAprvBinaryTree_print;
asn_constr_check_f UnsecuredAprvBinaryTree_constraint;
ber_type_decoder_f UnsecuredAprvBinaryTree_decode_ber;
der_type_encoder_f UnsecuredAprvBinaryTree_encode_der;
xer_type_decoder_f UnsecuredAprvBinaryTree_decode_xer;
xer_type_encoder_f UnsecuredAprvBinaryTree_encode_xer;
jer_type_encoder_f UnsecuredAprvBinaryTree_encode_jer;
oer_type_decoder_f UnsecuredAprvBinaryTree_decode_oer;
oer_type_encoder_f UnsecuredAprvBinaryTree_encode_oer;
per_type_decoder_f UnsecuredAprvBinaryTree_decode_uper;
per_type_encoder_f UnsecuredAprvBinaryTree_encode_uper;
per_type_decoder_f UnsecuredAprvBinaryTree_decode_aper;
per_type_encoder_f UnsecuredAprvBinaryTree_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _UnsecuredAprvBinaryTree_H_ */
#include "asn_internal.h"
