/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_VehicleSize_H_
#define	_VehicleSize_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Iso3833VehicleType.h"
#include "SpecialTransportType.h"
#include "VehicleLength.h"
#include "VehicleWidth.h"
#include "VehicleHeight.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleSize */
typedef struct VehicleSize {
	Iso3833VehicleType_t	 vehicleType;
	SpecialTransportType_t	*vehicleTransportedGoods;	/* OPTIONAL */
	VehicleLength_t	 vehicleLenth;
	VehicleWidth_t	 vehicleWidth;
	VehicleHeight_t	 vehicleHeight;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleSize_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleSize;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleSize_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleSize_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleSize_H_ */
#include "asn_internal.h"
