/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_VehicleCurrentStateContainer_H_
#define	_VehicleCurrentStateContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Speed.h"
#include "Wgs84Angle.h"
#include "VehicleSize.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ManoeuvreOverallStrategy;

/* VehicleCurrentStateContainer */
typedef struct VehicleCurrentStateContainer {
	struct ManoeuvreOverallStrategy	*manoeuvreOverallStrategy;	/* OPTIONAL */
	Speed_t	 vehicleSpeed;
	Wgs84Angle_t	 vehicleHeading;
	VehicleSize_t	 vehicleSize;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleCurrentStateContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleCurrentStateContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleCurrentStateContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleCurrentStateContainer_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ManoeuvreOverallStrategy.h"

#endif	/* _VehicleCurrentStateContainer_H_ */
#include "asn_internal.h"
