/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_WayPointType_H_
#define	_WayPointType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum WayPointType {
	WayPointType_startingWayPoint	= 0,
	WayPointType_intermediateWayPoint	= 1,
	WayPointType_endingWayPoint	= 2
} e_WayPointType;

/* WayPointType */
typedef long	 WayPointType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_WayPointType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_WayPointType;
extern const asn_INTEGER_specifics_t asn_SPC_WayPointType_specs_1;
asn_struct_free_f WayPointType_free;
asn_struct_print_f WayPointType_print;
asn_constr_check_f WayPointType_constraint;
ber_type_decoder_f WayPointType_decode_ber;
der_type_encoder_f WayPointType_encode_der;
xer_type_decoder_f WayPointType_decode_xer;
xer_type_encoder_f WayPointType_encode_xer;
jer_type_encoder_f WayPointType_encode_jer;
oer_type_decoder_f WayPointType_decode_oer;
oer_type_encoder_f WayPointType_encode_oer;
per_type_decoder_f WayPointType_decode_uper;
per_type_encoder_f WayPointType_encode_uper;
per_type_decoder_f WayPointType_decode_aper;
per_type_encoder_f WayPointType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _WayPointType_H_ */
#include "asn_internal.h"
