/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_WayPoint_H_
#define	_WayPoint_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PathPoint.h"

#ifdef __cplusplus
extern "C" {
#endif

/* WayPoint */
typedef PathPoint_t	 WayPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WayPoint;
asn_struct_free_f WayPoint_free;
asn_struct_print_f WayPoint_print;
asn_constr_check_f WayPoint_constraint;
ber_type_decoder_f WayPoint_decode_ber;
der_type_encoder_f WayPoint_encode_der;
xer_type_decoder_f WayPoint_decode_xer;
xer_type_encoder_f WayPoint_encode_xer;
jer_type_encoder_f WayPoint_encode_jer;
oer_type_decoder_f WayPoint_decode_oer;
oer_type_encoder_f WayPoint_encode_oer;
per_type_decoder_f WayPoint_decode_uper;
per_type_encoder_f WayPoint_encode_uper;
per_type_decoder_f WayPoint_decode_aper;
per_type_encoder_f WayPoint_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _WayPoint_H_ */
#include "asn_internal.h"
