/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_WrappedMcmInformationBlocks_H_
#define	_WrappedMcmInformationBlocks_H_


#include "asn_application.h"

/* Including external dependencies */
#include "McmBasicContainer.h"
#include "McmContainer.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* WrappedMcmInformationBlocks */
typedef struct WrappedMcmInformationBlocks {
	McmBasicContainer_t	 basicContainer;
	McmContainer_t	 mcmContainer;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WrappedMcmInformationBlocks_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WrappedMcmInformationBlocks;
extern asn_SEQUENCE_specifics_t asn_SPC_WrappedMcmInformationBlocks_specs_1;
extern asn_TYPE_member_t asn_MBR_WrappedMcmInformationBlocks_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _WrappedMcmInformationBlocks_H_ */
#include "asn_internal.h"
