/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#include "AcknowledgmentContainer.h"

asn_TYPE_member_t asn_MBR_AcknowledgmentContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AcknowledgmentContainer, acknowledgedType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_McmType,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"acknowledgedType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AcknowledgmentContainer, generationDeltaTime),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimestampIts,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"generationDeltaTime"
		},
};
static const ber_tlv_tag_t asn_DEF_AcknowledgmentContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AcknowledgmentContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* acknowledgedType */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* generationDeltaTime */
};
asn_SEQUENCE_specifics_t asn_SPC_AcknowledgmentContainer_specs_1 = {
	sizeof(struct AcknowledgmentContainer),
	offsetof(struct AcknowledgmentContainer, _asn_ctx),
	asn_MAP_AcknowledgmentContainer_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AcknowledgmentContainer = {
	"AcknowledgmentContainer",
	"AcknowledgmentContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_AcknowledgmentContainer_tags_1,
	sizeof(asn_DEF_AcknowledgmentContainer_tags_1)
		/sizeof(asn_DEF_AcknowledgmentContainer_tags_1[0]), /* 1 */
	asn_DEF_AcknowledgmentContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_AcknowledgmentContainer_tags_1)
		/sizeof(asn_DEF_AcknowledgmentContainer_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_AcknowledgmentContainer_1,
	2,	/* Elements count */
	&asn_SPC_AcknowledgmentContainer_specs_1	/* Additional specs */
};

