/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "./ASNfiles/ETSI CAM v1.4.1enh.asn"
 */

#include "AuxilliaryLinkRSSI.h"

int
AuxilliaryLinkRSSI_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -8000000 && value <= 10000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_AuxilliaryLinkRSSI_constr_1 CC_NOTUSED = {
	{ 4, 0 }	/* (-8000000..10000) */,
	-1};
asn_per_constraints_t asn_PER_type_AuxilliaryLinkRSSI_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 23, -1, -8000000,  10000 }	/* (-8000000..10000) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const ber_tlv_tag_t asn_DEF_AuxilliaryLinkRSSI_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
asn_TYPE_descriptor_t asn_DEF_AuxilliaryLinkRSSI = {
	"AuxilliaryLinkRSSI",
	"AuxilliaryLinkRSSI",
	&asn_OP_NativeInteger,
	asn_DEF_AuxilliaryLinkRSSI_tags_1,
	sizeof(asn_DEF_AuxilliaryLinkRSSI_tags_1)
		/sizeof(asn_DEF_AuxilliaryLinkRSSI_tags_1[0]), /* 1 */
	asn_DEF_AuxilliaryLinkRSSI_tags_1,	/* Same as above */
	sizeof(asn_DEF_AuxilliaryLinkRSSI_tags_1)
		/sizeof(asn_DEF_AuxilliaryLinkRSSI_tags_1[0]), /* 1 */
	{ &asn_OER_type_AuxilliaryLinkRSSI_constr_1, &asn_PER_type_AuxilliaryLinkRSSI_constr_1, AuxilliaryLinkRSSI_constraint },
	0, 0,	/* Defined elsewhere */
	0	/* No specifics */
};

