/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "ASNfiles/ETSI CAM v1.4.1enh.asn"
 */

#include "CamParametersEnhanced.h"

asn_TYPE_member_t asn_MBR_CamParametersEnhanced_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CamParametersEnhanced, basicContainer),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BasicContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"basicContainer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CamParametersEnhanced, highFrequencyContainer),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_HighFrequencyContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"highFrequencyContainer"
		},
	{ ATF_POINTER, 3, offsetof(struct CamParametersEnhanced, lowFrequencyContainer),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_LowFrequencyContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"lowFrequencyContainer"
		},
	{ ATF_POINTER, 2, offsetof(struct CamParametersEnhanced, specialVehicleContainer),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SpecialVehicleContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"specialVehicleContainer"
		},
	{ ATF_POINTER, 1, offsetof(struct CamParametersEnhanced, channelNodeStatusContainer),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChannelNodeStatusContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"channelNodeStatusContainer"
		},
};
static const int asn_MAP_CamParametersEnhanced_oms_1[] = { 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_CamParametersEnhanced_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CamParametersEnhanced_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* basicContainer */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* highFrequencyContainer */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* lowFrequencyContainer */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* specialVehicleContainer */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* channelNodeStatusContainer */
};
asn_SEQUENCE_specifics_t asn_SPC_CamParametersEnhanced_specs_1 = {
	sizeof(struct CamParametersEnhanced),
	offsetof(struct CamParametersEnhanced, _asn_ctx),
	asn_MAP_CamParametersEnhanced_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_CamParametersEnhanced_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CamParametersEnhanced = {
	"CamParametersEnhanced",
	"CamParametersEnhanced",
	&asn_OP_SEQUENCE,
	asn_DEF_CamParametersEnhanced_tags_1,
	sizeof(asn_DEF_CamParametersEnhanced_tags_1)
		/sizeof(asn_DEF_CamParametersEnhanced_tags_1[0]), /* 1 */
	asn_DEF_CamParametersEnhanced_tags_1,	/* Same as above */
	sizeof(asn_DEF_CamParametersEnhanced_tags_1)
		/sizeof(asn_DEF_CamParametersEnhanced_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CamParametersEnhanced_1,
	5,	/* Elements count */
	&asn_SPC_CamParametersEnhanced_specs_1	/* Additional specs */
};

