/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "ASNfiles/ETSI CAM v1.4.1enh.asn"
 */

#include "ChannelNodeStatusContainer.h"

asn_TYPE_member_t asn_MBR_ChannelNodeStatusContainer_1[] = {
	{ ATF_POINTER, 4, offsetof(struct ChannelNodeStatusContainer, auxilliaryLinkMac),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AuxilliaryLinkMac,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"auxilliaryLinkMac"
		},
	{ ATF_POINTER, 3, offsetof(struct ChannelNodeStatusContainer, auxilliaryLinkRSSI),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AuxilliaryLinkRSSI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"auxilliaryLinkRSSI"
		},
	{ ATF_POINTER, 2, offsetof(struct ChannelNodeStatusContainer, ipAddress),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IPAddr,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipAddress"
		},
	{ ATF_POINTER, 1, offsetof(struct ChannelNodeStatusContainer, publicIpAddress),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IPAddr,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"publicIpAddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChannelNodeStatusContainer, cpuLoad),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CPULoad,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cpuLoad"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChannelNodeStatusContainer, ramLoad),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RAMLoad,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ramLoad"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChannelNodeStatusContainer, gpuLoad),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GPULoad,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gpuLoad"
		},
	{ ATF_POINTER, 3, offsetof(struct ChannelNodeStatusContainer, extraComputationDeviceCpuLoad),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CPULoad,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"extraComputationDeviceCpuLoad"
		},
	{ ATF_POINTER, 2, offsetof(struct ChannelNodeStatusContainer, extraComputationDeviceRamLoad),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RAMLoad,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"extraComputationDeviceRamLoad"
		},
	{ ATF_POINTER, 1, offsetof(struct ChannelNodeStatusContainer, extraComputationDeciceGpuLoad),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GPULoad,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"extraComputationDeciceGpuLoad"
		},
};
static const int asn_MAP_ChannelNodeStatusContainer_oms_1[] = { 0, 1, 2, 3, 7, 8, 9 };
static const ber_tlv_tag_t asn_DEF_ChannelNodeStatusContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ChannelNodeStatusContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* auxilliaryLinkMac */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* auxilliaryLinkRSSI */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ipAddress */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* publicIpAddress */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* cpuLoad */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* ramLoad */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* gpuLoad */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* extraComputationDeviceCpuLoad */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* extraComputationDeviceRamLoad */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 } /* extraComputationDeciceGpuLoad */
};
asn_SEQUENCE_specifics_t asn_SPC_ChannelNodeStatusContainer_specs_1 = {
	sizeof(struct ChannelNodeStatusContainer),
	offsetof(struct ChannelNodeStatusContainer, _asn_ctx),
	asn_MAP_ChannelNodeStatusContainer_tag2el_1,
	10,	/* Count of tags in the map */
	asn_MAP_ChannelNodeStatusContainer_oms_1,	/* Optional members */
	7, 0,	/* Root/Additions */
	10,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ChannelNodeStatusContainer = {
	"ChannelNodeStatusContainer",
	"ChannelNodeStatusContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ChannelNodeStatusContainer_tags_1,
	sizeof(asn_DEF_ChannelNodeStatusContainer_tags_1)
		/sizeof(asn_DEF_ChannelNodeStatusContainer_tags_1[0]), /* 1 */
	asn_DEF_ChannelNodeStatusContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_ChannelNodeStatusContainer_tags_1)
		/sizeof(asn_DEF_ChannelNodeStatusContainer_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ChannelNodeStatusContainer_1,
	10,	/* Elements count */
	&asn_SPC_ChannelNodeStatusContainer_specs_1	/* Additional specs */
};

