/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#include "ManoeuvreCooperationGoal.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_ManoeuvreCooperationGoal_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ManoeuvreCooperationGoal_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  6 }	/* (0..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_ManoeuvreCooperationGoal_value2enum_1[] = {
	{ 0,	19,	"vehicleInterception" },
	{ 1,	10,	"roadSafety" },
	{ 2,	10,	"humanHelth" },
	{ 3,	21,	"emergencyIntervention" },
	{ 4,	24,	"roadOperatorIntervention" },
	{ 5,	22,	"localTrafficManagement" },
	{ 6,	23,	"globalTrafficManagement" }
};
static const unsigned int asn_MAP_ManoeuvreCooperationGoal_enum2value_1[] = {
	3,	/* emergencyIntervention(3) */
	6,	/* globalTrafficManagement(6) */
	2,	/* humanHelth(2) */
	5,	/* localTrafficManagement(5) */
	4,	/* roadOperatorIntervention(4) */
	1,	/* roadSafety(1) */
	0	/* vehicleInterception(0) */
};
const asn_INTEGER_specifics_t asn_SPC_ManoeuvreCooperationGoal_specs_1 = {
	asn_MAP_ManoeuvreCooperationGoal_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_ManoeuvreCooperationGoal_enum2value_1,	/* N => "tag"; sorted by N */
	7,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ManoeuvreCooperationGoal_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ManoeuvreCooperationGoal = {
	"ManoeuvreCooperationGoal",
	"ManoeuvreCooperationGoal",
	&asn_OP_NativeEnumerated,
	asn_DEF_ManoeuvreCooperationGoal_tags_1,
	sizeof(asn_DEF_ManoeuvreCooperationGoal_tags_1)
		/sizeof(asn_DEF_ManoeuvreCooperationGoal_tags_1[0]), /* 1 */
	asn_DEF_ManoeuvreCooperationGoal_tags_1,	/* Same as above */
	sizeof(asn_DEF_ManoeuvreCooperationGoal_tags_1)
		/sizeof(asn_DEF_ManoeuvreCooperationGoal_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_ManoeuvreCooperationGoal_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ManoeuvreCooperationGoal_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ManoeuvreCooperationGoal_specs_1	/* Additional specs */
};

