/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#include "McmType.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_McmType_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_McmType_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  9 }	/* (0..9) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_McmType_value2enum_1[] = {
	{ 0,	6,	"intent" },
	{ 1,	7,	"request" },
	{ 2,	8,	"response" },
	{ 3,	11,	"reservation" },
	{ 4,	11,	"termination" },
	{ 5,	19,	"cancellationRequest" },
	{ 6,	29,	"emergencyManoeuvreReservation" },
	{ 7,	15,	"executionStatus" },
	{ 8,	5,	"offer" },
	{ 9,	14,	"acknowledgment" }
};
static const unsigned int asn_MAP_McmType_enum2value_1[] = {
	9,	/* acknowledgment(9) */
	5,	/* cancellationRequest(5) */
	6,	/* emergencyManoeuvreReservation(6) */
	7,	/* executionStatus(7) */
	0,	/* intent(0) */
	8,	/* offer(8) */
	1,	/* request(1) */
	3,	/* reservation(3) */
	2,	/* response(2) */
	4	/* termination(4) */
};
const asn_INTEGER_specifics_t asn_SPC_McmType_specs_1 = {
	asn_MAP_McmType_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_McmType_enum2value_1,	/* N => "tag"; sorted by N */
	10,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_McmType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_McmType = {
	"McmType",
	"McmType",
	&asn_OP_NativeEnumerated,
	asn_DEF_McmType_tags_1,
	sizeof(asn_DEF_McmType_tags_1)
		/sizeof(asn_DEF_McmType_tags_1[0]), /* 1 */
	asn_DEF_McmType_tags_1,	/* Same as above */
	sizeof(asn_DEF_McmType_tags_1)
		/sizeof(asn_DEF_McmType_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_McmType_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_McmType_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_McmType_specs_1	/* Additional specs */
};

