/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#include "TerminationContainer.h"

static const ber_tlv_tag_t asn_DEF_TerminationContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SEQUENCE_specifics_t asn_SPC_TerminationContainer_specs_1 = {
	sizeof(struct TerminationContainer),
	offsetof(struct TerminationContainer, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TerminationContainer = {
	"TerminationContainer",
	"TerminationContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_TerminationContainer_tags_1,
	sizeof(asn_DEF_TerminationContainer_tags_1)
		/sizeof(asn_DEF_TerminationContainer_tags_1[0]), /* 1 */
	asn_DEF_TerminationContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_TerminationContainer_tags_1)
		/sizeof(asn_DEF_TerminationContainer_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	0, 0,	/* No members */
	&asn_SPC_TerminationContainer_specs_1	/* Additional specs */
};

