/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#include "WayPoint.h"

/*
 * This type is implemented using PathPoint,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_WayPoint_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_WayPoint = {
	"WayPoint",
	"WayPoint",
	&asn_OP_SEQUENCE,
	asn_DEF_WayPoint_tags_1,
	sizeof(asn_DEF_WayPoint_tags_1)
		/sizeof(asn_DEF_WayPoint_tags_1[0]), /* 1 */
	asn_DEF_WayPoint_tags_1,	/* Same as above */
	sizeof(asn_DEF_WayPoint_tags_1)
		/sizeof(asn_DEF_WayPoint_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_PathPoint_1,
	2,	/* Elements count */
	&asn_SPC_PathPoint_specs_1	/* Additional specs */
};

